### ISSUE TITLE
Some DSPs have not uint16_t etc. It seems to be better use uint_fast16_t

### ISSUE THREAD

**Issue by TYuD** [dvidelabs/flatcc#100]

**Comment by derosier** [comment]
This is not recommended at all.  uint16_t is a C99 standard data type with _exactly_ 16-bits. uint_fast16_t is defined as a unsigned integer that is fastest on the platform that can hold _at_least_ 16 bits. The fast variants are less likely to be implemented on more compilers than the sized one, and it seems odd to me that  your compiler would have uint_fast16_t when it doesn't have uint16_t.

I'd recommend you create a compat header that defines uint16_t to something that works on your platform. That would be much better than making flatcc broken to the rest of the world so it works for the specific architecture/toolchain you're working on.

All you have to do is create and include a compat header ahead of including the flatcc generated headers. Have that file have something like:
    typedef uint_fast16_t uint16_t;

**Comment by mikkelfj** [comment]
uint_fast16_t is definitely not a solution because flatbuffers must ensure that a 16-bit wide field is stored as a 16-bit field while uint_fast16_t is only guaranteed to be at least 16 bit, but could for example also be 32 bit. Also, it would break interface expectations for most users.

Do you have concrete example or a specific use case that needs to be resolved?

You can use a struct with two uint8_t fields to model a 16-bit type if you need that and if you can control the schema (as opposed to needing to stay compatible with someone elses schema).

This won't remove compile errors even if you don't use uint16_t, but you can then define them to arbitrary types before including flatcc headers.

It is possible to redefine 16 bit accessors (endian neutral read/write operations) to use another native type.

The core flatbuffer types are defined here

- https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_types.h

The actual accessors methods that reads and writes the different integer types including 16 bit types etc. are defined in

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_accessors.h

included via

- https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_endian.h
- https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_flatbuffers.h

**Comment by mikkelfj** [comment]
I did not see Steve's answer when writing mine, but I agree. Only, if  you define uint16_t to anything like uint_fast16_t or similar, do not actually create a schema that depends on it.

Also be aware of the flatbuffers_voffset_t type in flatbuffer_types.h which is also a 16 bit type defaulting to uint16_t and this MUST be 16 bit for all buffers.

**Comment by mikkelfj** [comment]
If you really do not care about compatibility with the rest of the world, it is likely that defining uint16_t to uint32_t or to uint_fast16_t will work. You could define flatbuffers_voffset_t to uint8_t because very often you do not use in excess of 200 fields in a table. But if you do this, it will be your own custom format optimized for DSP's, not a flatbuffer compatible format.

**Comment by TYuD** [comment]
mikkelfj, derosier! Thanks for your answers. I only begin to familiarize with a flatbuffer and a flatcc. The ideas of the flatbuffer are attractive, and I am looking for use flatcc in my system (PCs+DSPs+MCUs). Of course it is only permissible to use a flatbuffer compatible format (format of data packets, transferring over the net). What I meant in my post about uint16_t does not relate to format of data packets. It relates to runtime code: de/serialization functions etc. I think this code should use uint_fast16_t rather than uint16_t for compilers variety. 

Your tooltip to look at flatcc_accessors.h seams to be a solution (with some overhead of performance). I am going to learn it. Can you give me any advices? Below are fragments of stdint.h of my compilers.

Thanks!

// -------------------------------------- DSP compiler: 
typedef _Int32t int32_t;
typedef _Uint32t uint32_t;

typedef _Int32t int_least8_t;
typedef _Int32t int_least16_t;
typedef _Uint32t uint_least8_t;
typedef _Uint32t uint_least16_t;
typedef _Int32t int_least32_t;
typedef _Uint32t uint_least32_t;

typedef _Int32t int_fast8_t;
typedef _Int32t int_fast16_t;
typedef _Uint32t uint_fast8_t;
typedef _Uint32t uint_fast16_t;
typedef _Int32t int_fast32_t;
typedef _Uint32t uint_fast32_t;

typedef _ULonglong uint64_t;
typedef _Longlong int_least64_t;
typedef _ULonglong uint_least64_t;
typedef _Longlong int_fast64_t;
typedef _ULonglong uint_fast64_t;

// -------------------------------------- MCU compiler: 
    typedef          int    int16_t;
    typedef unsigned int   uint16_t;
    typedef          long   int32_t;
    typedef unsigned long  uint32_t;
    typedef          long long  int64_t;
    typedef unsigned long long uint64_t;

    typedef  int16_t  int_least8_t;
    typedef uint16_t uint_least8_t;
    typedef  int16_t  int_least16_t;
    typedef uint16_t uint_least16_t;
    typedef  int32_t  int_least32_t;
    typedef uint32_t uint_least32_t;
    typedef  int64_t  int_least64_t;
    typedef uint64_t uint_least64_t;

    typedef  int16_t  int_fast8_t;
    typedef uint16_t uint_fast8_t;
    typedef  int16_t  int_fast16_t;
    typedef uint16_t uint_fast16_t;
    typedef  int32_t  int_fast32_t;
    typedef uint32_t uint_fast32_t;
    typedef  int64_t  int_fast64_t;
    typedef uint64_t uint_fast64_t;

**Comment by mikkelfj** [comment]
Thanks for explaining. The accessors do not have overhead when you have a decent optimizing compiler. Typically they are just a pointer load/store and sometimes a byteswap if platform is big endian. The functions just make sure the proper operstions are chosen.

It seems that your DSP compiler is not able to deal with 16-bit words. Therefore it cannot support standard flatbuffers. Fixing the accessors application side is not enough since the binary data can be 16-bit.

If you use struct buffers (without vtables) and inly use 32-bit schema fields then you can define uint16 to anything as it won’t be used. However, struct buffers are limited to structs and are probably only supported by flatcc - even if theoretically standard.

**Comment by mikkelfj** [comment]
Even if you could change accessors, for example by reading 32 bits and shifting (with some overhead as you say), it will not work with structs that contain 16-bit fields. But otherwise - yes - despite my previous comment it could possibly work.

**Comment by mikkelfj** [comment]
You need to be very careful about alignment and test if you you should shift or mask, and make sure reading 16-bits outside the buffer is OK. You can assume that 16-bit fields are aligned to 16-bits in the buffer.

**Comment by mikkelfj** [comment]
If you can make it work, and you really put a lot of effort into it, including test and documentation, it could possible be added to flatcc. But it could not be an entirely out of the box experience.
Long term flatcc considers supporting flatcc_types.h files for dealing with large flatbuffers beyond 32GB, and it already supports a native big endian variant in a separate branch (a single config flag switch).

A flatbuffers a nested data strucuture with a table that contains fields. This fields can be other tables, structs, vectors etc.

A struct buffer is flatbuffer where the top-most data structure is a struct and it an only contain other structs. It is essentially the same as a memcpy of a standard C struct, except it handles issues like portable alignment, packing, and endianness. The official FlatBuffers doc does hint at having structs as root objects, but I don't think it has been widely implemented. Also, structs cannot contain vectors or strings or any other kind of pointers (offsets).

**Comment by mikkelfj** [comment]
Closing, but you are welcome to write here if you need more information, or reopen if you think have something that affects the flatcc project.

**Comment by craigbarnes** [comment]
> The fast variants are less likely to be implemented on more compilers than the sized one

@derosier That's the exact opposite of the truth. According to ISO C99 §7.8.11.1 the `{u,}int_{fast,least}{8,16,32,64}_t` types are "required". The `{u,}int{8,16,32,64}_t` types are optional.
