### ISSUE TITLE
Print JSON question

### ISSUE THREAD

**Issue by dmitryme** [dvidelabs/flatcc#105]
Hello, 
Can flatcc json printer prints to JSON data encoded by Python encoder from flatbuffers library? Or it is incompatibe with data encoded by Python or other languages?

**Comment by mikkelfj** [comment]
Yes, it should. If you find that it doesn't for some reason, there is a bug in at least one of the libraries.

**Comment by dmitryme** [comment]
Even more, C decoder can't decoder Python encoded data. It seems like I am doing something wrong... 

Full code available [here](https://github.com/dmitryme/flat_world)

Here is a schema:

`namespace proto;
table Order
{
   id: uint32;
}
file_identifier "v001";
root_type Order;`

Python encoder/decoder CAN both encode/decode self and decode C-encoded data:

```python

import flatbuffers as fb
from python.proto import Order

# encode
b = fb.Builder(0)

Order.OrderStart(b)
Order.OrderAddId(b, 100)
o = Order.OrderEnd(b)

b.Finish(o)
out = bytes(b.Output())

# s = ""
# for i in out:
    # s += "0x{:02x}, ".format(i)
# print(s)

# decode self
order = Order.Order.GetRootAsOrder(out, 0)
print(order.Id())

# decode C-encoded Order
c_enc = b'\x08\x00\x00\x00\x76\x30\x30\x31\xf8\xff\xff\xff\x64\x00\x00\x00\x06\x00\x08\x00\x04\x00'

order = Order.Order.GetRootAsOrder(out, 0)
print(order.Id())
```
But C encoder/decoder crashed on assert during decoding Python encoded data

```c

#include "c/proto_builder.h"
#include "c/proto_json_printer.h"
#include <stdio.h>
#include <assert.h>

int32_t main()
{
   // encode 
   flatcc_builder_t b;
   flatcc_builder_init(&b);

   proto_Order_start_as_root(&b);
   proto_Order_id_add(&b, 100);
   proto_Order_end_as_root(&b);
   size_t size = 0;
   void* buf = flatcc_builder_finalize_aligned_buffer(&b, &size);

   /*for(size_t i = 0; i < size; ++i)*/
   /*{*/
      /*printf("\\x%02x", ((unsigned char*)buf)[i]);*/
   /*}*/
   /*printf("\n");*/

   {
      // decode self
      proto_Order_table_t t = proto_Order_as_root(buf);
      printf("%d\n", proto_Order_id_get(t));
   }

   {
      // print self
      flatcc_json_printer_t ctx;
      char json[4096] = {};
      flatcc_json_printer_init_buffer(&ctx, json, sizeof(json));
      proto_print_json(&ctx, buf, size);
      printf("%s\n", json);
   }

   {
      // decode python encoded Order 
      const char buf[] = {0x0c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x00, 0x08, 0x00, 0x04, 0x00, 0x06, 0x00, 0x00, 0x00, 0x64, 0x00, 0x00, 0x00};
      proto_Order_table_t t = proto_Order_as_root(buf);
      assert(t); // FAILED!!!
      printf("%d\n", proto_Order_id_get(t));
   }

   return 0;
}
```

**Comment by mikkelfj** [comment]
The buffer has no identifier, so to override the default identifier check, you need to set a null identifier to indicate that you do not care about the value (at byte offset 4..7).

    proto_Order_as_root_with_identifier(buf, 0);

because the buffer has no file identifier as expected. You could also manually set the identifier at byte offset 4..7 to "v001". I am a bit concerned though: why is the buffer content at that offset

 0x00, 0x00, 0x06, 0x00,

that looks like garbage, at least it could have been all 0x00 if not set.
The C encoder has set the verifier to \x76\x30\x30\x31 which is v100 in ASCII.

Also note that strictly speaking that const char buf is not aligned. This works on x86, but not everywhere. Especially the verifier might complain if you tried to use it. It is always good to run the verifier first, when testing integration. It would have said the identifier is missing.

**Comment by mikkelfj** [comment]
Oh wait, perhaps the 4 bytes in the python buffer is not garbage, but just a missing identifier The field can actually be absent - you don't really know except that it does not match expectations. It is valid to omit an identifier, but flatcc needs to be told that this is OK. (The reason it is unknown is that the first 4 bytes point to the root table, so the next 4 bytes could be any data referenced from elsewhere).

**Comment by dmitryme** [comment]
You right, If I add file identifier by hand C encoding/printing works well.

> It is valid to omit an identifier, but flatcc needs to be told that this is OK
How can I told to flatcc to omit file identifier ?

BTW, there is no file identifier in Python flatbuffers yet. Still under development.

**Comment by mikkelfj** [comment]
for reading, as i wrote:

    proto_Order_as_root_with_identifier(buf, 0);

instead of 

    proto_Order_as_root(buf);

I tested this, and it does print JSON without an assertion.

Or, (I think), if you remove file_identifier from the schema. See documentation for details.

For building, you pass a null identifier in a similar manner and it will not get stored (I think).

NOTE: I was wrong in saying that you can just add the identifier manually because you will need to make space to do that, and that can cause various problems so I won't even try to explain. IFF you are sure there is already an identifier, then you can overwrite it with what you want. But that is not the case here, I was wrong in my first answer.

**Comment by dmitryme** [comment]
Thanks a lot!

**Comment by mikkelfj** [comment]
The reason you could overwrite byte 4..7 with the identifier is just pure luck. You were overwriting some unused padding and vtable header fields only need for verification.
