### ISSUE TITLE
Possible missing 'break' statements in semantics.c

### ISSUE THREAD

**Issue by atonizzo** [dvidelabs/flatcc#110]
A basic ```cmake ../ & make``` ends up in two errors related to fall-through case statements in semantics.c,
inside the `switch` statement in `function validate_table_attr()` [-Werror=implicit-fallthrough=].

Since you test for the very same condition in both `case` statements I doubt the fall-through is intentional.
Adding `break` statements seems to solve the issue and from the looks of the code it seems that even if
the fall-through was intentional and the idea was to reach the `continue` statement, the missing `break`
statements lead to the same behavior.

Am I missing anything?

**Comment by mikkelfj** [comment]
> Am I missing anything?

No, I am missing something. fixed in  7511cb0  

As you say, there is no impact on behaviour, but it is clearly a bug. Also, due to gcc being increasingly aggressive, all intentional fall throughs now have to marked /* Fall through */. I have no idea why I do not see an error here - maybe because I am not working with latest gcc (Travis don't do that, and neither do MacOs).

For this project `continue` is conventionally used to skip irrelevant symbols while `break` is often used on matched symbols becasuse there are sometimes shared post processing before continuing the loop, though not here.
