### ISSUE TITLE
Compile Error: "Format" %X expects 'unsigned int'

### ISSUE THREAD

**Issue by innerand** [dvidelabs/flatcc#119]
`%X` expects `unsigned int` but `uin32_t` may be anything. 

https://github.com/dvidelabs/flatcc/blob/fbaba3cc982cdc5e88f54125b6d2af448ba464e0/include/flatcc/portable/grisu3_print.h#L192

Using macros from `inttypes.h` for printf and scanf format specifiers may solve that problem
```c
if ((u64 << 1) > 0xFFE0000000000000ULL) return sprintf(dst, "NaN(%08"PRIx32"%08"PRIx32")", (uint32_t)(u64 >> 32), (uint32_t)(u64));
```
[[patch](https://gist.github.com/innerand/3742801609ac52df7c668d98cdf096f2)]

**Comment by mikkelfj** [comment]
Sorry, I missed this issue until now.
Yes you are correct. And you can't use unsigned int because it can also be anything, including 16-bit.
I need to look a bit more into this because I'm not sure about the dependencies on these macros in the particular code - it is at the very bottom of everything. Alternatively a fast integer print from pprint.h should be copied here.

Is this urgently needing a fix?

**Comment by mikkelfj** [comment]
I added a custom nan printer. It also removes the dependency on sprintf except for the single case where grisu3 is not able to print the value on its own.

Does this solve the problem for you? Please review  https://github.com/dvidelabs/flatcc/commit/de2740ac6f26f45faf08b9cd11472b45844eed2b as I didn't really test the NaN output.
