### ISSUE TITLE
Flatcc incorrect behaviour: compiling enum as a vector

### ISSUE THREAD

**Issue by zednun** [dvidelabs/flatcc#126]
I was trying to compile a schema (enum Status).
part of it is:
table GetStatusResponse {
	status:Status;
}
enum Status: byte {
	status1 = 0,
	status2 = 1,
	status3 = 2,
	status4 = 3
}
but it doesnt compile it as an enum. it compiles as a vector.
can anyone help me?

**Comment by mikkelfj** [comment]
A vector is defined for enums even you you don't need a vector. Flatcc generates all operators for all types it sees.

You still have the underlying enum type and the vector does no harm, nor does it consume any space in compiled code if you do not use it.

**Comment by mikkelfj** [comment]
In the generated reader code this is line the defines the scalar status field:

```c
__flatbuffers_define_scalar_field(0, GetStatusResponse, status, Status, Status_enum_t, INT8_C(0))
```
It does not use the vector.

**Comment by mikkelfj** [comment]
But, I suspect what confuses you is not the enum as vector since that is hidden in macro definitions. It it the GetStatusResponse table which is also defined as a vector, but unrelated to enums specifically:

```c
static inline size_t GetStatusResponse_vec_len(GetStatusResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline GetStatusResponse_table_t GetStatusResponse_vec_at(GetStatusResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(GetStatusResponse_table_t, vec, i, 0)
```

This makes it possible to have  a vector of GetStatusResponse tables, for example if you include the schema in another schema file. Flatcc always produces the same output regardless of how a schema is included.

Technically the table vector ought to be hidden in a macro definition to remove unnecessary "noise" in the output, but I never got around to that.
