### ISSUE TITLE
flatbuffers_common_verifier.h

### ISSUE THREAD

**Issue by VangrunderbeekArnoud** [dvidelabs/flatcc#128]
`flatcc -a monster_test.fbs` doesn't produce `flatbuffers_common_verifier.h` as stated in the tutorial/documentation.

When I include `monster_test_verifier.h` in my project, without any line of code, I got linking errors:
```
undefined reference to 'flatcc_verify_union_field'
undefined reference to 'flatcc_verify_table_field'
undefined reference to 'flatcc_verify_string_field'
```

I compile with `-lflatcc, -I../include and -L../lib` options.

I don't know how to solve this, would appreciate a little help if possible?

**Comment by mikkelfj** [comment]
There is no generated common verifier. Does the documentation mention this? Indeed it does - that changed a long time ago. Will fix.

There is a `#include "flatcc/flatcc_verifier.h"` included in generated schema specific verifier. You need `-I include` in your path if the project flatcc directory is the current working directory.

You must also either include `src/runtime/verifier.c` in your project, or link with `lib/flatccrt.a`.

**Comment by mikkelfj** [comment]
Fixed documentation. Let me know if this works for you.

**Comment by mikkelfj** [comment]
While `-lflatcc` should work, it is better to use `-lflatccrt` because `-lflatcc` includes the entire flatcc compiler.

**Comment by VangrunderbeekArnoud** [comment]
Dear, thank you **very** much for your answer. Using -flatccrt instead of -flatcc solved the problem. I think this is maybe a bug? With the demo project using -flatcc and including the Monster_verifier.h an error occurs. When changing the lib the error is solved.

How can I buy you a coffee? Cheers, Arnoud.

**Comment by mikkelfj** [comment]
I'm not sure if the verifier is supposed to be included in the flatcc library - the fact that it works for the builder has more to do with flatcc depends on the builder.c source, but not the verifier. I think - I didn't look closely.

As to coffee, thanks, but I already have good setup - including backup water since I happen to have a water leak so the main tap is closed atm.

**Comment by VangrunderbeekArnoud** [comment]
Oke! Mikkel, I have another small question. Is there any documentation already about error messaging? I got the error message `table field not aligned` but don't know what this means and how to solve this...

**Comment by VangrunderbeekArnoud** [comment]
I already found the problem, thank you very much!

**Comment by mikkelfj** [comment]
For future reference: you can read more about how to debug buffers here:
https://github.com/dvidelabs/flatcc#debugging-a-buffer

The verifier does not tell exactly where it goes wrong because it is written for speed rather than keeping track of the path it traverses when seeing an error. You can get more information by enabling tracing as per above link, and by setting break points og debugging to assert points, you can see the name of verifier functions and these give a strong hint about where things go wrong.

The message requires some understanding of what is valid in flatbuffers:
https://github.com/dvidelabs/flatcc/blob/master/doc/binary-format.md

**Comment by VangrunderbeekArnoud** [comment]
Thanks for the reference, I'll take a look !
