### ISSUE TITLE
flatcc_builder_finalize_aligned_buffer and FLATCC_ALIGNED_FREE mismatch

### ISSUE THREAD

**Issue by postwait** [dvidelabs/flatcc#131]
flatcc_buffer_finalize_aligned_buffer will use a certain alignment allocation mechanism that depends on compiler flags.  This mechanism is static in the object file for the runtime.

The free method is also dependent on compiler flags, but those of the application, not the run-time.  This can cause the flatccrt run-time to perform and aligned alloc in a way that the client cannot predict nor select an match free mechanism.

The flatccrt should provide a `void flatcc_buffer_aligned_free(void *)` function that explicitly matches the alignment mechanism used in the `flatcc_buffer_finalize_aligned_buffer` it exposes to allow for safe freeing.

**Comment by postwait** [comment]
This was addressed in 0.5.0, I'm running old code.

*IGNORE ME*

**Comment by mikkelfj** [comment]
The point is valid, but as you say, already addressed.

New on master, only a few days old, is similar flatcc_builder_free operation in case you have overridden the standard malloc/free by redefining FLATCC_BUILDER_FREE - which could happen on FreeRTOS and other esoteric systems - no-one ever had a problem with that, presumably because you are forced to use the correct free operation if 'free' is not available.
