### ISSUE TITLE
identifier name conflict (was: Is Xcode 11 supported? )

### ISSUE THREAD

**Issue by kennycarruthers** [dvidelabs/flatcc#135]
I've used `flatcc` to generate all files using the -a flag. I'm then including the generated header file into a basic macOS application using Xcode. 

However, whenever I try and build, an error is generated when Xcode attempts to expand one of the many macros. Perhaps there's an additional Xcode setting I need to change or that I have set incorrectly? 

(This is with Xcode 11.2.1. I've tried setting the `Build Setting - C Language Dialect` to both `gnu11` and `c11` but to no avail.) 

The error is as follows: 

```
In file included from /.../FlatBufferBridge.c:10:
/.../CollectiveRecord+Generated_C.h:41:1: error: expected identifier or '('
__flatbuffers_define_string_field(0, CollectiveRecordFlatBuffer, identifier, 1)
^
In file included from /.../FlatBufferBridge.c:10:
In file included from /.../CollectiveRecord+Generated_C.h:7:
/.../flatbuffers_common_reader.h:96:36: note: expanded from macro '__flatbuffers_define_string_field'
static inline flatbuffers_string_t N ## _ ## NK(N ## _table_t t__tmp)\
                                   ^
<scratch space>:38:1: note: expanded from here
CollectiveRecordFlatBuffer_identifier
^
In file included from /.../FlatBufferBridge.c:10:
.../CollectiveRecord+Generated_C.h:26:47: note: expanded from macro 'CollectiveRecordFlatBuffer_identifier'
#define CollectiveRecordFlatBuffer_identifier flatbuffers_identifier
                                              ^
.../CollectiveRecord+Generated_C.h:15:32: note: expanded from macro 'flatbuffers_identifier'
#define flatbuffers_identifier "FBCT"
```

**Comment by mikkelfj** [comment]
It should be supported but I haven't explicitly tested with XCode as an environment, only the MacOS clang CLI tools. It appears that you might be missing some include paths. If low-level macros are not defined you can get all sorts of strange errors.

**Comment by mikkelfj** [comment]
Perhaps try a CLI setup first like here: https://github.com/dvidelabs/flatcc#introduction
Then replace with you own schema and create a minimal project, then compare the compiler settings to your XCode projects if you can get a log when it is building. It should be very basic.

**Comment by mikkelfj** [comment]
This is the clang version I last tested with:

```
clang --version
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by kennycarruthers** [comment]
I created a new Objective-C Xcode project using Apple's default settings. I eventually narrowed down the error to the FlatBuffer schema file. If one of the properties in the schema is named `identifier`, then Xcode fails to build with the above mentioned error. If I change the property name to anything other than `identifier`, then it works properly. 

Is `identifier` a reserved property name in FlatBuffers? (I appear to be able to use it without any issues in C++.) 

The following schema causes the error: 

```
table Record {
  identifier:string;
}

root_type Record;

```

**Comment by mikkelfj** [comment]
"identifier" is not reserved in the schema syntax, but there are some names that can conflict in the generated code because it would be very tedious to avoid all possible name conflicts.

I have seen this problem before. The reason is that every table gets an automatically named `<table-name>_<identifier>` which is used for naming buffers with such a table as root.

The functions generated to read fields generally have the form `<namespace>_<table-name>_<field-name>`. These are more likely to conflict than other functions. By using the `-g` option all read accessors are named `<namespace>_<table-name>_<field-name>_get`, i.e. with a `_get_` suffix. 

Therefore you should be able to fix the problem by either renaming identifer as you did, or by using the `-g` option and modify your user level code to use _get suffix when reading fields.

**Comment by mikkelfj** [comment]
The same problem was discussed here: https://github.com/dvidelabs/flatcc/issues/99#issuecomment-433741969

**Comment by mikkelfj** [comment]
See also https://github.com/dvidelabs/flatcc#potential-name-conflicts

**Comment by kennycarruthers** [comment]
Thanks for the quick reply. Using the `-g` option doesn't appear to address the issue for me. I still get build errors: 

`expected identifier or '('`

Changing the property name definitely addresses the issue.

**Comment by kennycarruthers** [comment]
Follow-up... 

If I change the field type from `string` to `int`, then the `-g` flag does solve the problem. But if the field type is left as `string` and the field name is left as `identifier`, then the `-g` flag does not appear to resolve the original issue.

**Comment by mikkelfj** [comment]
Hmm that is strange. That could be a bug in the way the -g is handled.

**Comment by mikkelfj** [comment]
flatcc really ought to check the most likely names to cause conficts but it can't check all possible conflicts.

**Comment by kennycarruthers** [comment]
Ok. Well thanks for the quick reply and follow-up. The original issue is now understood and a workaround is available should I wish to change my schemas. Thank you

**Comment by mikkelfj** [comment]
You are welcome.

There is no obvious mistake in the code generation:
(the `-g` option is cgen_no_conflicts)

https://github.com/dvidelabs/flatcc/blob/cc3436d7e8b7628d79c463cb51468f545020bc39/src/compiler/codegen_c_reader.c#L578-L598

**Comment by mikkelfj** [comment]
The reason the `-g` option works for scalar types (e.g. int) but not for strings is because the builder has an extra indirection in macro expansion.

For example given the table:

```
table foo {
    identifier: string;
}
```

There is a `foo_identifier` the names the file identifier for that table, here
`#define foo_identifier flatbuffers_identifier`
There is also a macro call to 
`__flatbuffers_build_string_field(0, flatbuffers_, foo_identifier, foo)`
but here foo_identifier is a prefix used to create methods such as `foo_identifier_add` and so forth.
This is not a problem in simple cases which is why integer types work. But the string type (and other complex field types), call further macros. The additional macro expansion triggers evaluation of `foo_identifier` which yields undesirable results. The builder does not actual create name conflicts, but the macro name prefix argument still fails.

Unfortunately it is non-trivial to fix except for simply not generating the `foo_identifier` file identifier, but that could break a lot of existing code.

**Comment by mikkelfj** [comment]
I have fixed the issue by renaming `<table-name>_identifier` to `<table-name>_file_identifier`. The old form is still generated for backwards compatibility, but only when there are no conflicts. This old form is deprecated and will eventually be removed. The generated name is mostly used by higher level functions to automatically add the correct file identifier when creating a buffer.

Please verify that 9a31bef solves the issue for you (latest master as of now).

**Comment by kennycarruthers** [comment]
Thanks for the quick follow-up and resolution, much appreciated.
