### ISSUE TITLE
Question: Is it possible to disable any function calls in flatcc that result in _read or _write calls

### ISSUE THREAD

**Issue by bturner1273** [dvidelabs/flatcc#136]
I have this running on a micro and don't want to overwrite/provide dummy functions for _read or _write in case anything else I am using relys on them. I am thinking the functions causing issues with 'undefined ref to _read' or _write errors could be printf, fprintf, or sprintf used in flatcc

**Comment by mikkelfj** [comment]
Do you have any concrete experienced problems?

There shouldn't be any such calls in the core logic although examples of course frequently print results. If you enable certain debug flags, you can force printing of trace information in the verifier and possibly elsewhere, but they shouldn't be the norm.

There _might_ be assertions in debug that could trigger I/O calls if an assertion fails but in that case you can just build in release mode to avoid that problem. If that is insufficient, you will need to hunt for asserts in builder.c and verifier.c and possibly a few other places.

JSON parsing and printing also do not use such operations directly since they operate on memory buffers.

**Comment by bturner1273** [comment]
My only issue is if I don't provide dummy functions i.e.
```c
#include <stdio.h>
#include <stddef.h>
ssize_t _write(int fd, const void *buf, size_t nbytes) {
	return 0;
}

ssize_t _read(int fd, void *buf, size_t count) {
	return 0;
}
```
and I have flatc included in the project. Then I get errors:
'Undefined reference to `_read`'
and 
'Undefined reference to `_write`' 

I am going to try to build in release mode and see what happens now

**Comment by bturner1273** [comment]
I do still get those errors which is odd if nothing should be doing io in release mode

**Comment by mikkelfj** [comment]
I did a search on stdio in the source, and it is included in the JSON printer, and if you define certain debug flags in the verifier. I could have missed something. Flatcc is definitely such that you shouldn't have a dependency on stdio unless you want to.

It's hard for me to help any further with the information I have, but if you can isolate what part of the code makes a reference to _read or _write, I can have a look. I would say that it is a bug if you can easily avoid these calls.

For a start please make sure the problem isn't in the top-level driver code of yours, or in any test cases which clearly will make such calls.

**Comment by mikkelfj** [comment]
If you link libflatccrt.a, try to compile directly with src/runtime/builder.c instead. Any other files in the runtime library shouldn't not be necessary for a basic project that reads and write buffers. Then introduce more files if you need and see if that changes anything.

It could be that there is some unused function the runtime library that makes a reference to an I/O function, and if you linker does not optimize that out, you could get the problem.

**Comment by bturner1273** [comment]
Yeah I just tried that with only builder.c and I am still getting that for whatever reason. I'll keep looking at this and give you an update if I find anything wacky
