### ISSUE TITLE
Incorrect assessment of presence of posix_memalign

### ISSUE THREAD

**Issue by Panometric** [dvidelabs/flatcc#138]
My platform is [GNU ARM](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads/7-2018-q2-update)  (STM32 Cube), using newlib which does not have posix_memalign().
Yet in `palighned_alloc.h`:

```
#elif (defined(__STDC__) && __STDC__ && defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L)
```
and
```
(defined _GNU_SOURCE) || ((_XOPEN_SOURCE + 0) >= 600) || (_POSIX_C_SOURCE + 0) >= 200112L
```
are true which leads to a linker error. 

I don't understand all the permutations you are trying to detect here. but these two lines are incorrect for my platform.  When I comment them out, it seems to work fine. 

Linker options are:
`-mcpu=cortex-m4 -T".\STM32L476RGTX_FLASH.ld" --specs=nosys.specs -Wl,-Map="${ProjName}.map" -Wl,--gc-sections -static --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group`

Is there any further information I can provide that could be used to make a better choice?

**Comment by mikkelfj** [comment]
As a starting point:

It may be somewhat related to https://github.com/dvidelabs/flatcc/issues/77 where that was an issue with pstdalign.h, and also in newlib issue mentioned in this comment https://github.com/dvidelabs/flatcc/issues/77#ref-issue-294878878

This was addressed in commit https://github.com/dvidelabs/flatcc/commit/6a3a7a0db9b339a108edba9af400555a6fd2d6a1#diff-87d9fd24a6fa5e1f3b35f4068f163eb5
and https://github.com/dvidelabs/flatcc/commit/e6043f1909438901666aa1e60fa871bdbfd4adb1#diff-87d9fd24a6fa5e1f3b35f4068f163eb5

Note that newlib is difficult to deal with because it explicitly wants to be mistaken for glibc such that users do not write special code that can break things. But that doesn't work for cases such as the portable library that aims to add missing features.

Perhaps this information can guide you in coming up with a suggested change.

**Comment by mikkelfj** [comment]
I'm not sure how much the above will help in this case, although both are related to newlib.

As a workaround you could try to define `-DPORTABLE_POSIX_MEMALIGN=0` in the C build flags.
I think this should disable posix memalign, and if you are not compiling with compliant C11, you should , with a bit of luck, then go to the default implementation.

Also note that newlib seems to be going back and forth with some memalign implementation, so you might also be able to define memalign as posix_memalign?

**Comment by mikkelfj** [comment]
@Panometric Please let me know if defining DPORTABLE_POSIX_MEMALIGN works for you.
It is a really tricky area to make changes and I can't make the on my own without being able to reproduce. Even with reproduction support, it is complicated because it might break other areas. POSIX_MEMALIGN detection is down to specific GCC versions based on user feedback.

As much as I'd like to make flatcc work seamlessly with newlib, I'm not sure it is possible, at least not with the information I have at the moment.

**Comment by Panometric** [comment]
@mikkelfj Sorry that did not work, because @ [line 63](https://github.com/dvidelabs/flatcc/blob/f30b928f04b3c27552114f62dd7fe9433286a33f/include/flatcc/portable/paligned_alloc.h#L63)
`#if !defined(PORTABLE_POSIX_MEMALIGN)` is false, it falls back into the same trap of evaluating:
_POSIX_C_SOURCE which is 200809, which sets PORTABLE_POSIX_MEMALIGN back to 1. 

So the way I got it to work was to remove:
54-55:
```
#elif (defined(__STDC__) && __STDC__ && defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L)
#define PORTABLE_C11_ALIGNED_ALLOC 1
```
and set 66 to:
`#if 0`

I also don't understand all the permutations you are trying to cover so I can't make a better suggestion.

**Comment by mikkelfj** [comment]
Well, if it is not possible to automate the detection, at least it should be possible to supply a flag the forces the desired behaviour. I'll have a look at the issue you mention and see if it can fixed or if a new config flag is needed.

Would you be OK with setting a config flag equal or similar to PORTABLE_POSIX_MEMALIGN, provided that it works for your case?

**Comment by Panometric** [comment]
Sure, of course.

**Comment by mikkelfj** [comment]
@Panometric 

Sorry for the delay.

I have now been reading carefully through the code. I do not understand the problem with line https://github.com/dvidelabs/flatcc/blob/f30b928f04b3c27552114f62dd7fe9433286a33f/include/flatcc/portable/paligned_alloc.h#L63

If you have -DPORTABLE_POSIX_MEMALIGN=0 in the build flags, the block at line 63 should not execute at all. Later on there are only 3 options: C11 standard aligned_alloc, posix memalign, or a generic implementation. Of these 3 options, C11 takes precedence, but if that is not triggered, there is not way that POSIX is chosen when DPORTABLE_POSIX_MEMALIGN is set to 0, unless I am missing something. Hence it should force a generic choice.

So, what am I missing? And are you sure you have configured the build flag as suggested - e.g. defining without a value instead of setting it to 0?

https://github.com/dvidelabs/flatcc/blob/f30b928f04b3c27552114f62dd7fe9433286a33f/include/flatcc/portable/paligned_alloc.h#L96

will not trigger if PORTABLE_POSIX_MEMALIGN is defined to 0.

You can define `PORTABLE_DEBUG_ALIGNED_ALLOC` to see which branch is taken in the code.

**Comment by mikkelfj** [comment]
I added the following documentation note on branch "issue138"

https://github.com/dvidelabs/flatcc/commit/165808a08ee53201e9d0827a781efcf02cc17f46

But since I'm not sure it is working, I won't merge it for now. Open to suggestions.

**Comment by Panometric** [comment]
I must have made an error earlier. I used :
`#define PORTABLE_POSIX_MEMALIGN 0 ` at the top of the file which I thought would be the same. 

Using: ` -DPORTABLE_POSIX_MEMALIGN=0` in the build flags I do not get the linker error.   But I also don't get the __portable_aligned_alloc definition, which I suppose is fine if newlib is OK as is. 

There might be a way to simplify this,
`#ifdef __NEWLIB__ ` is true on my platform if that helps.

**Comment by mikkelfj** [comment]
That I don't understand:

First, `#define PORTABLE_POSIX_MEMALIGN 0` at the top of the file should behave exactly the same as defining a compiler flag.

Second, if you do not enter the POSIX branch, you should get a generic inline function defined for `__portable_aligned_alloc`. The macro `aligned_alloc` is then defined to this function. If that did not happen, some test cases would break. You can run `scripts/test.sh` to verify.

That is, you should enter

https://github.com/dvidelabs/flatcc/blob/f30b928f04b3c27552114f62dd7fe9433286a33f/include/flatcc/portable/paligned_alloc.h#L129

... assuming I'm not missing something.

As to __NEWLIB__, that must be a change in policy, or previously undocumented. Unfortunately this can probably not be relied upon for older newlib versions, but still, when present, it can be used.

I added https://github.com/dvidelabs/flatcc/commit/6d3910fd35192c88cb9aceaa57271eb827f99498
to yet another branch issue138_2 with newlib detection.

How does that work?

**Comment by mikkelfj** [comment]
Note that if you use std=C11, you will not enter the POSIX branch or the generic branch. In that case it is assumed that aligned_alloc is provided by the library. But if you have that configuration, you wouldn't have seen the POSIX error.

**Comment by mikkelfj** [comment]
@Panometric without further feedback, I can't really do anything with this potential issue so I am inclined to close as is.

**Comment by Panometric** [comment]
@mikkelfj sorry for the confusion. It looks like what has occurred is that my build environment has changed, which caused the error to go away. Now, even when I remove `PORTABLE_POSIX_MEMALIGN` it's happy. Unfortunately, this was a result of my whole IDE and libraries of STM32Cube getting upgraded, so I can't easily backtrack.  That said, unless someone else uses the same older version, it should not be an issue, so lets close this.

**Comment by mikkelfj** [comment]
Thanks for the update, glad it worked out in the end.
