### ISSUE TITLE
null value in json not supported in parsing

### ISSUE THREAD

**Issue by elvinio** [dvidelabs/flatcc#14]
Hi,

I am seeing an issue where the data has a null value, eg. "field1":null and the parser generated fails with "expected string" error.

Looking at the generated parser.h, the buf = flatcc_json_parser_string_start(ctx, buf, end) returns the error as the buffer does not begin with ".

Is null value supported? If it is, how do I specify this in the schema?

Regards
Elvin

**Comment by mikkelfj** [comment]
Hi Elvin,

unfortunately the FlatBuffers format is not very precise about null values. I briefly mentioned it here: https://github.com/dvidelabs/flatcc#null-values

The JSON parser follows FlatBuffers. If a string field could accept null as a value, it would be an absent flatbuffer string field and when printing it again, the field would disappear because there is no way to decide between missing and null values. Therefore null is not supported in the parser. The solution is to make the field absent, or alternatively allow unknown field names (via the runtime flag `flatcc_json_parser_f_skip_unknown`) and then only use null values on unknown fields.

The parser does internally have flatcc_json_parser_null, but it is only used for skipping unknown fields and when it needs to backtrack union types where first parse is untyped json.

Technically we could add a flag to allow null values on known fields and treat them as missing, but since it sort of breaks Googles flatc json format I chose not to.

**Comment by elvinio** [comment]
Okay, I see the issue with differentiating between missing field and a field with null value now. Thanks for explaining.

In case someone needs to parse null and do not need this differentiation, this is a quick hack. 
Add in line 545 in codegen_c_json_parser.c:
```
 544     } else if (is_string) {
 545         println(out, "if(memcmp(buf, \"null\", 4) == 0){buf+=4; continue;}");
 546         println(out, "buf = flatcc_json_parser_string_start(ctx, buf, end);");
```

When reading, check if the field is present. If the field is not present, then the field was either missing or had a null value.

**Comment by mikkelfj** [comment]
To do this in a general way would require a lot more work because more types must be handled, but if you wish to add a pull request with a new flatcc_json_parser_f_allow_null, feel free to do so - flatcc_json_parser_null should be used in preference over the snippet above - it does largely the same - but haven't studied the details.

It might involve modifications to the code generator and it should not slow down performance until the parser would otherwise fail. It may also be combined with a new flag in https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_rtconfig.h

Overall, a null value should be treated the same as if the field was missing or was an unknown field.
