### ISSUE TITLE
Flatcc codegen truncates precision for default value for floats

### ISSUE THREAD

**Issue by ivayloen** [dvidelabs/flatcc#140]
I have a very simple schema with a float and a default value for it : 

```
namespace Eclectic;

table FooBar {
    val1    : float32 = 1e-18;
}
file_identifier "NOOB";
root_type FooBar;
```

The generated header truncates the significant digits after the decimal point to just 6, which results in wrong code : 
```
__flatbuffers_define_scalar_field(0, Eclectic_FooBar, val1, flatbuffers_float, float, 0.000000f)
```

This doesn't happen with C++ Flatbuffers codegen. I don't know how much work this is but ideally the codegen should just copy the default value literal to the header (as do C++ Flatbuffers).

[bugreport.tar.gz](https://github.com/dvidelabs/flatcc/files/4308736/bugreport.tar.gz)

**Comment by mikkelfj** [comment]
This is not necessarily a bug. It should not loose information, if it does, it should be fixed. The literal string form is not copied, rather, the internal floating point representation is printed. The internal representation is initially stored in 64 bit floats and later printed with (hopefully) sufficient precision.

Even an infinite sequence of fractional digits is not enough to represent  some floating point values, and even a short sequence of fractional digits cannot always be represented exactly in floating point representation. In general a floating point value can have multiple equally valid printed representations. A big problem in printing such values is finding an algorithm that can print the shortest representation fast.

In your case the question is if 1e-18 is closer to zero than to the next higher representable value in 32-bit floating point, otherwise it will be represented as a zero at the latest when converted to 32-bit floats before printing. Then no amount of printing precision will change that. Nor will it matter because even if an alternative non-zero representation were printed, it would still be converted into zero by the C compiler (if 1e-18 is closer to zero).

In you test program in the attached bug report, you use 1e-18 and compare to 1-e30. I have not tried your program, but I will note that you are testing double (i.e. 64-bit) constants in C, not 32-bit constants, so you need to an 'f' suffix to the constants.

**Comment by mikkelfj** [comment]
I believe the code in question is the following:

https://github.com/dvidelabs/flatcc/blob/57dd5198ef8c96b1ebd733c718fe310b1753fb20/src/compiler/codegen_c.h#L264-L270
via
https://github.com/dvidelabs/flatcc/blob/57dd5198ef8c96b1ebd733c718fe310b1753fb20/src/compiler/codegen_c_reader.c#L1609-L1612

Here the internal 64-bit float is first printed to an fb_literal temporary string buffer based on the type of the value to be printed, here fb_float which is a 32-bit value. The value cast to 32-bit before printing using the %ff printf formatter.

The %f formatter defaults to 6 digits, not full precision. So this is indeed a bug. I believe the JSON printer handles this better.

It should have printed using %.9g" for float32 and %.17g for float64.
However, since we printing to C code, we need to always print a decimal point, and also add an f suffix for 32-bit floats. This is done by adding a '#' flag. Thus the formatter should be: "%#.9gf" for floats and "%#.17g" for double.

I have pushed this to master, please have a look and thanks for reporting this.

**Comment by mikkelfj** [comment]
The source is now

https://github.com/dvidelabs/flatcc/blob/0f5345bc82786e41d3b93921cf7b5db647c49d77/src/compiler/codegen_c.h#L264-L276

**Comment by ivayloen** [comment]
Thank you for the quick reply @mikkelfj ! This should do the trick, I had a similar workaround for myself :) 

In an ideal solution the schema parser should just read the schema default value and verify it's a proper float representation, while the codegen just uses the same default value literal in the generated header, i.e codegen shouldn't change the representation at all. I looked through the code and it seemed like a substantial amount of work. This solution is good enough for me. Thanks again!

Out of curiosity, does it make sense to use FLT_DECIMAL_DIG and DBL_DECIMAL_DIG instead of hardcoding 9 and 17 respectively ? Can those change across platform ?

**Comment by mikkelfj** [comment]
I could use the string representation but conceptually, the string is for the schema language while the generated code is for the C language, so an exact translation would just defer the loss of information, and hence it is not worth the complexity. The schema text representation could also be hexadecimal, so it could get rather adventurous having it work on all C compilers. 

I did consider FLT_DECIMAL_DIG etc. but that would be specific to the host machine running the flatc compiler and not the machine running the generated code. Furthermore, the precision is defined to be IEEE 32/64 bit floats for the flatbuffer format and here 9/17 will always be enough. The host or target C compiler could use another floating point standard, but it is very unlikely except for dedicated signalprocessor applications and the like and it would not be compatible with the flatbuffers format, so irrelevant. Having the C source be valid IEEE float for compatible C compilers is the best you can get.

**Comment by mikkelfj** [comment]
For what it is worth, I think the `member->symbol` object (or something like it) has an offset and length to the input text token representing the floating point value. This is used in error reporting, but it could likely be used to print the value directly. But as I mentioned, it will not really solve anything and could risk breaking things.
