### ISSUE TITLE
Full Compatibility with flatbuffers

### ISSUE THREAD

**Issue by shiranbi** [dvidelabs/flatcc#15]
Question:
Is it guaranteed that there is full compatibility with flatbuffers?
I want to build the buffer with flatcc and read it on another machine with flatbuffers.
If compatibility is guaranteed where can I find with which version of flatbuffers each flatcc version is compatible?
Thanks

**Comment by mikkelfj** [comment]
To avoid confusion, please observe that flatc refers to googles flatc flatbuffers compiler, and flatcc refers to, well, flatcc.

It is guaranteed for all versions (unless there is a very old flatc compiler that is incompatible with a more recent version of itself). flatcc has followed the published spec and hasn't been released before interop tests have passed. As I recall, there hasn't been found any bugs preventing any version of flatcc from handling the binary format, or the schema syntax, correctly in typical use cases. flatcc was initially tested against flatbuffers version 1.1, but the binary format itself hasn't changed. Versioning of flatbuffers (flatc) and flatcc mostly relate to new features (such as JSON or RPC support), improved language interfaces, and bug fixes. RPC is a new schema syntax that recent flatcc parses though it does not generate code for it - you can see the changelog for details: https://github.com/dvidelabs/flatcc/blob/master/CHANGELOG.md

The flatcc schema parser is fairly aggressive in validating the schema to prevent accidental incorrect code generation (such as using an invalid enum initializer value). It may miss some issues, and it may also be more strict than flatc on other issues, but these are subtle differences and if the schema parses on the both compilers, chances are the schema is pretty solid, and most importantly, if the schema is correct, it should work.

Of course you might find subtle differences in corner cases - but these could also occur between two languages both generated from flatc. If any critical issues are found, they will be fixed, but tests are fairly solid.

flatcc on big endian should be at least version 0.4.0, but it will read buffers generated on little endian platforms by older flatcc compilers, or by other flatbuffer builders based on flatc. I cannot speak for big endian support from other generators, though in theory it should work on both little and big endian platforms. In praxis it is difficult to test which is why flatcc didn't do it until 0.4.0 where a user of a big endian system were willing to help with testing and tracking down problems.

If you are still concerned, I recommend taking advantage of both flatcc's and flatc's binary verifiers and use them in production or test runs until confidence has been built.

**Comment by mikkelfj** [comment]
Adding the following forum thread as it is related - here I answer questions on relation to main flatbuffer project and concerns related to future maintenance:

https://groups.google.com/forum/#!msg/flatbuffers/aRlfD5e-d48/SzQDSuE-DgAJ
