### ISSUE TITLE
A few -Wconversion and -Wsign-conversion warnings

### ISSUE THREAD

**Issue by mcrlc** [dvidelabs/flatcc#151]
In the file `include/flatcc/flatcc_identifier.h` there are a few conversion issues. Since this header is included from `flatbuffers_common_reader.h` I couldn't build it in my project.
I used GCC 7.5 with the following flags (partial list) `-Wconversion -Wsign-conversion -Werror`.
I'll open a PR soon to point at the problems.

**Comment by mikkelfj** [comment]
FYI: there were recently some fixes in this area:
https://github.com/dvidelabs/flatcc/pull/147

**Comment by mcrlc** [comment]
Thanks. I actually looked at this PR before posting and it looks like it refers to different lines.
BTW: there are many more `-Wconversion` and `-Wsign-conversion` warnings, most of them I found in `builder.c`, but they look less trivial to fix. I might try some other time.

**Comment by mikkelfj** [comment]
Yesterday I added `-Wsign-conversion` and `-Wconversion` to clang builds. Today I added `-Wsign-conversion` which required a lot more changes in addition to clang - it's broken for GCC 4.7 so disabled there (can't handle ternary operator). I also took your suggested cast from the PR since it wasn't a widespread problem. I tried to fix `-Wconversion` and did make some changes, but ultimately I stopped because `x = x + 1` or even `x = x + 1u` requires a cast, and `n = -n;` would also require a cast. That isn't reasonable.

I believe -Wsign-conversion is important in some cases, but it does leave a lot of ugly code that doesn't make it worthwhile in most cases. I might remove support for this warning in GCC in the future because GCC keeps getting more and more aggressive at the expense of code readability and portability. clang seems to strike a better balance although it also requires lots of casts.

Please let me know what you think. Changes are on master.

**Comment by mikkelfj** [comment]
You can also see the build in the ci-more branch on travis - it tracks many more compiler versions but is only built when I explicitly push to that branch.

**Comment by mcrlc** [comment]
Saw the changes. This actually fixed many of the other warnings we had. Your case about -Wsign-conversion is very reasonable, and I wish GCC didn't make it harder to use it.
Anyway, I'll close my PR now as it's no longer relevant. Thank you for maintaining this project!

**Comment by mikkelfj** [comment]
Thanks, I'll be closing this issue. If you find some particular warning that you want fixed without being intrusive to the code, feel free to submit at new PR, but as discussed, the target is to support clang warnings not GCC.
