### ISSUE TITLE
Are finalized flat buffers mutable? 

### ISSUE THREAD

**Issue by jjh8326** [dvidelabs/flatcc#165]
I found a discussion which has a 2019 post from a google engineer saying that there are options for mutating flat buffers today. My question is did these changes in flatc carry over into flatcc and if so can you please explain how to do this?

[Link to discussion](https://groups.google.com/g/flatbuffers/c/noV9D2cgS4A)

**Comment by mikkelfj** [comment]
Flatcc does not support mutation because it is inherently unsafe: Even if a buffer is verified, it is possible to construct malicious buffer where to different fields occupy the same space. Mutating one field could lead to buffer overrun accessing the other.

Also, mutation is quite limited in Flatc: you can only mutate simple scalars, and perhaps scalar arrays that doesn't grow. You can get around this using an object API, but that is slow (I have no personal experience with this).

That said, if you really know what you are doing, there is a _ptr suffix to field accessors in flatcc (from memory its been a while). You can cast this point to a non-const value and thereby mutate the buffer. However, you must take care of endian translation yourself if you are on a big endian platform. There is a number of helpers in flatcc headers that can help with that - see https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_accessors.h

Flatcc also support mutation in one special case: to sort arrays. Flatcc does not support sorting arrays while building the buffer, but you can sort the finalized buffer in-place without using extra memory. This is only intended to be used on buffers you fully control, like right after building the buffer.

**Comment by mikkelfj** [comment]
Here is a test case that gets an array pointer using _ptr suffix. I'm not sure if ptr is also available for regular scalar fields, but I would not reject a qualified PR to add this if it is missing.

https://github.com/dvidelabs/flatcc/blob/ce931d0e34b9a4a9dd69939f2d5860c781b42d8b/test/monster_test/monster_test.c#L1874-L1891

**Comment by jjh8326** [comment]
Thank you so much for this in-depth response! This is exactly the answer I was looking for.

**Comment by mikkelfj** [comment]
You are welcome. Feel free to reopen if you have more questions.
