### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by cdesjardins** [dvidelabs/flatcc#224]
We have been waiting for the next release of flatcc for some time now, I am particularly interested in the changes to FLATCC_ASSERT. Is there a plan for a new release any time soon?

**Comment by mikkelfj** [comment]
Yes, a release is long overdue. Unrelated circumstances has caused delays. I have one pull request where code needs to be refactored but otherwise I think we can release soon.

**Comment by cdesjardins** [comment]
Great to hear, I will keep my eyes open for this. Let me know if there is anything I can do to help.

**Comment by mikkelfj** [comment]
@cdesjardins 
> Let me know if there is anything I can do to help.

Well, if you are up for it:
https://github.com/dvidelabs/flatcc/pull/216

There are some boolean tests on commandline flags and program settings that should only be used in the cli file since it is kind of messy but they are tested elsewhere to drive logic forward. It may be that a new setting is needed which can be set in the cli file. I haven't looked that closely yet.

**Comment by mikkelfj** [comment]
0.6.1 has been released, but without merging outstanding pull requests.
