### ISSUE TITLE
The internal define `fallthrough` leaks to usercode

### ISSUE THREAD

**Issue by bjosv** [dvidelabs/flatcc#247]
When a source file includes both `flatcc` and  `Boost` the following problem appears:
```
staging/include/boost/config/compiler/clang.hpp:314:26: error: missing ')' after '('
#if !__has_cpp_attribute(fallthrough) || __cplusplus < 201406L
                         ^~~~~~~~~~~
staging/include/flatcc/portable/pattributes.h:74:22: note: expanded from macro 'fallthrough'
# define fallthrough pattribute(fallthrough)
                     ^~~~~~~~~~~~~~~~~~~~~~~
staging/include/flatcc/portable/pattributes.h:69:23: note: expanded from macro 'pattribute'
#define pattribute(x) pattribute_##x
                      ^~~~~~~~~~~~~~
<scratch space>:358:1: note: expanded from here
pattribute_fallthrough
^~~~~~~~~~~~~~~~~~~~~~
staging/include/flatcc/portable/pattributes.h:63:46: note: expanded from macro 'pattribute_fallthrough'
# define pattribute_fallthrough __attribute__((__fallthrough__))
                                             ^
staging/include/boost/config/compiler/clang.hpp:314:25: note: to match this '('
#if !__has_cpp_attribute(fallthrough) || __cplusplus < 201406L
                        ^
1 error generated.
```

Is there a suggestion of a remedy to a problems like this?

I am new to flatcc's code, but there seem to be a use of both `fallthrough` and `pattribute(fallthrough)`.
Would it make sense to replace all `fallthrough` with `pattribute(fallthrough)` or is there a reason why using both variants?

**Comment by mikkelfj** [comment]
To answer your last question:

> Would it make sense to replace all fallthrough with pattribute(fallthrough) or is there a reason why using both variants?

pattribute(x) is just a mechanism to define attibutes consistently in the portable library. It is also used as a backdoor to use when the portable attributes cannot be exposed (see PORTABLE_EXPOSE_ATTRIBUTES).  Replacing with pattribute(fallthough)` is not desireable because flatcc (ideally) does not depend on portable features when the a modern standard feature is present. `attribute(fallthrough)` would be a better appoach, but that would require implementing `attribute` for older compiles, which likely makes the problem worse. Replacing with `/* fallthrough */` has been done before, but later GCC ruined that.

I think what is going wrong is that portable decides that fallthrough needs to be defined and thus defines it.
Boost goes through the same line of thinking, but the check for if the attribute has been defined fails because fallthrough is a defined symbol (by flatcc) and this apparantly causes problems.

For other attributes and similar keywords it is common to have a x_is_defined symbol to check for, but that was not available for fallthrough.

To avoid exposing fallthrough, assuming boost takes care of that, you could define `-DPORTABLE_EXPOSE_ATTRIBUTES=1` in the build settings.

You might also get away with defining PORTABLE_HAS_C_ATTRIBUTE or PORTABLE_HAS_ATTRIBUTE or maybe it works to reorder the include files so Boost gets a chance to define first. I'm not sure if it is possible to check for boos without relying on include order.

However, flatcc will not work without `fallthrough` defined somehow because 1. that is how it is implemented, and 2. the alternatives are worse. You can thank GCC for this mess.

**Comment by mikkelfj** [comment]
`fallthrough;` is actually neither a standard nor a compiler extension. Clang uses `FALLTHROUGH` for backwards compat.: https://clang.llvm.org/docs/LanguageExtensions.html
but the Linux kernel does use `fallthrough`
https://www.kernel.org/doc/html/latest/process/deprecated.html?highlight=fallthrough#implicit-switch-case-fall-through
More discussion here:
https://stackoverflow.com/questions/45129741/gcc-7-wimplicit-fallthrough-warnings-and-portable-way-to-clear-them

So flatcc chose the Linux kernel convention - which breaks Boost.

**Comment by bjosv** [comment]
Thanks for your thorough reply, much appreciated!
It doesn't seem easy to please all the variants of compilers and versions regarding `fallthrough`
We will experiment a bit with `-DPORTABLE_EXPOSE_ATTRIBUTES=0` or see if there would be a need to patch `pattributes.h`.

**Comment by mikkelfj** [comment]
@bjosv If you wan't to contribute, we can rewrite all uses of `fallthrough;` to use `goto lbl_xxx;` and add labels instead of falling through.

**Comment by bjosv** [comment]
Sure, I have seen that there is something similar in `external/lex/luthor.c`.
I will prepare a PR to see how it can be.

**Comment by mikkelfj** [comment]
Maybe separate the PR in two commits, one for runtime, and one for compiler / CLI.
