### ISSUE TITLE
flatcc --schema has a limit on the number of enums.

### ISSUE THREAD

**Issue by n3npq** [dvidelabs/flatcc#32]
While writing a schema with a very large enum, I see this assertion failure

flatcc -ad --json --schema rpmtag.fbs
flatcc: /X/src/FLATBUFFERS/flatcc/src/runtime/builder.c:1396: flatcc_builder_create_offset_vector_direct: Assertion `vec[i] != 0' failed.

Removing --schema generates other files correctly.

The issue SHOULD be easy to reproduce: create an enum with something like 50 members.

My rpmtag.fbs schema is attached.
[rpmtag.fbs.gz](https://github.com/dvidelabs/flatcc/files/702312/rpmtag.fbs.gz)

**Comment by n3npq** [comment]
The subject line SHOULD be
    flatcc --schema has a limit on the number of enum members.
Apologies for ambiguous "size".

**Comment by mikkelfj** [comment]
This is incorrect use of the builder api. The vector of table representing enum values was assumed to be stable, but adding the individual enum tables would eventually force the builder stack to reallocate rendering the reserved vec object invalid. Now uses the vec_push_start/end api which is slightly slower but simpler and safer.

Fixed in 55547e3
