### ISSUE TITLE
Support C-like hex/octal values in enum assignments

### ISSUE THREAD

**Issue by n3npq** [dvidelabs/flatcc#33]
(A NICETOHAVE enhancement, nothing wrong with decimal even if sometimes annoying ;-)

As a C programmer, I often find that hex/octal and simple arithmetic/logic expressions useful.

For example:

enum FOO:uint {
    A = 256+1,
    B = 0xffff,
    C = (0x10000 | 1),
    Z = 0x3fffffff,
}

**Comment by mikkelfj** [comment]
I agree, at least with hex notation, and I did consider this, but as I recall, rejected it because the main Google flatc compiler did not support it, and I wanted to avoid unnecessary incompatibilities in the schema. This may have changed though. The lexer already handles hex numbers if enabled.

That said, it could be enabled by compile time flags. For illustration, the JSON printer optionally supports hex notation for floating points because it is the only way to transfer exact numbers, and it is also much faster.

On the expression syntax, this may be overengineering and could be a can of worms (symbolic constants, scope resolution etc.), but it is a good proposal. I suggest discussing this on the flatbuffers forum.

There is also a compile time flag to handle non-incrementing enums which goes against googles flatc rules.

The config flags can be assigned in the build script without changing the config file.
https://github.com/dvidelabs/flatcc/blob/master/config/config.h

FLATCC_STRICT_ENUM_INIT
FLATCC_ASCENDING_ENUM
FLATCC_ALLOW_BOOLEAN_CONVERSION
FLATCC_HIDE_LATER_ENUM

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_rtconfig.h
FLATCC_JSON_PRINT_HEX_FLOAT

**Comment by mikkelfj** [comment]
flatc now supports -0x02 style constants, and it has been added. Closing as octal support is probably not a good idea and expressions are not compatible, and borderline out of scope. Might reopen after discussion in forum if flatc wants to support it.

166f98e

**Comment by n3npq** [comment]
You might want to consider octal, too.

More generally, I'm not sure how portability is enhanced by pparseint.h treating a hex/signed constant differently than an integer constant.  POSIX strtoll(3) is widely available, with implementations with almost any desired license, and handles binary/octal/decimal/hex (and even base36 which can be useful for a compact string representation).

(aside)
Portability also applies to POSIX strftime(3) and attaching format string through an attribute as the first step to adding date/time typedef's.

All depends on what you consider "portable": there are certainly non-POSIX contexts that might need "support".

Thanks for hex integer support no matter what ;-)

**Comment by mikkelfj** [comment]
On octals: Julia has a different octal syntax from C, more logical, but different. Octals in C are prone to hard to trace errors from using leading zeroes, and some consider it an ill-conceived idea. Considering how infrequent octals are, and that you have enums with bit flags and hex encoding, it is not first thing on my mind.

You may be right on the stroll for this use case, I didn't really think about it last night since the parser already used parse_integer for decimals.

There may be concerns related to both overflow checking for different integer types and also sensitivity to current locale, even for integers since a trailing decimal point is considered an error. Current locale dependencies also sometimes slows things down.

The primary use case is for flatcc is json printing and parsing where numeric handling easily consumes 50% of the total processing time. The portable library provides a mean to get typesafe and very fast conversions, something that is always a mess to deal with when you consider all the facts.

The history goes: strtod wasn't really good/fast/safe (no end marker) for float parsing, so float parsing was added with grisu3 interface. Likewise float printing is a performance bottleneck and grisu3 support was added. Integer printing can be done much faster than certain standard calls, and then it was natural to provide integer parsing for symmetri although there are less to be gained performance wise. And then hex follow naturally since parse_integer was already used in the parser. You may argue this is not really a porting problem, but it is a recurring issue when you consider all the facts.

Note: float parsing still depends on strod in some special cases, but the interface is designed so it can be removed entirely. MSVC had a runtime library for strtod that called strlen on input buffer at one point.

Let's see how strftime works if/when we get to that point.

**Comment by n3npq** [comment]
AGREED: octal in C is error prone and there are many divergent formats, not only octal.

AGREED: grisu3 is a nice solution to uncouple from, say, POSIX vagaries. But consider the grisu3 maintenance cost of (say, I jest here ;-) adding "long long long double" support instead of using POSIX strtod(3). Its the uncoupling, not the implementation,  from POSIX and other standards that makes "double" meaningfully portable in flatcc+grisu3. JMHO, YMMV.

Hmmm ... I'm unaware of any L10N localization related to floats/doubles, "Ick!" is so. That isn't true for date/time formats which are buried under most "libc" strftime(3) implementations. Dragging in locales bloats one's code quickly. OTOH, using a POSIX interface with an internal implementation to remove L10N is what I would have done.

JMHO YMMV, thans for hex no matter how implemented.

**Comment by mikkelfj** [comment]
Great. BTW, flatcc, especially the runtime, cannot rely fully on posix. E.g. posix_memalign is a non-starter. There is nothing wrong in portable adding a posix function, but it needs to be replaceable when it isn't there, and it shouldn't hijack a proper implementation, hence the different naming.

portable isn't supposed to handle everything, or handle the same as some posix function, so long long double is likely not a priority, but I get your point. If you are only on FreeBSD, it is easy to use portable Posix calls. If not, you can fault the platform, but it won't help you much when your implementation of strtod only supports double and float.

strftime certainly is sensitive to the current local for some arguments.

you are welcome.

**Comment by mikkelfj** [comment]
For the record, another driver for parse_integer and friends is the need to parse a buffer that is not zero terminated. strtoll does not take and end or length argument. This is often needed in parsing, especially to avoid buffer overruns without reallocating a buffer. Openbsd strtonum handles the range check problem, but not the end marker.

**Comment by n3npq** [comment]
AGREED: There is nothing wrong in portable adding a posix function.

The generalization to strntoll(3) is obvious: my original point wrote pparseint.h
would be to unify integer parsing, not have separate parses for int and hex (and octal and ...).

The choice of API is less important than unifying int & hex parsing: stroll(3) was just an obvious API.

**Comment by mikkelfj** [comment]
Another issue with strtoll is that ll is that it is not guaranteed to be 64 bits. I'm not sure if you noticed, but there is a whole familiy of parse_in32_integer functions. strntoll might work on the end marker, but isn't widely supported.  The primary objective is safe predictable identical results on all platforms, and an option to make it fast when possible (via platform or new implementation).

Yet another issue with using a posix function like, say strtoll, is that either it always works, and you don't need it, or you need a fallback. If the fallback is equally good, there is no point of the Posix function. For endian conversion the fallback is not equally good - it is slow - for integer conversion the fallback may be better because it is specialized and then Posix looses relevance. For aligned allocation, posix_memalign isn't portable, but is the best choice on platforms that supports it, but just one among several.

As to combining hex and int. I'm not sure either way is best, I'm not even sure the 0x/0X prefix should be required. However, it allows you to only accept what want and to have a fast path for the expected type. Also, it is symmetrical with print_integer. If you combined int and hex, you also would have to consider octal as you mention, and you loose control. Many JSON parsers accidentally accept more than they should according to the standard, for this reason, just with strtod. But that is also a good thing  because then you can have hex floats - but still - it should have been an intentional choice. So you end up having to parse the prefix anyway. But as I said, from another perspective you may well be right - but perhaps it is then better to include a portable strtoll implementation, and likewise if you need it.

It is also relevant to somewhat restrict the feature set of portable. If portable attempts to cover too much ground, it will stop being portable, or it will become very large.

**Comment by mikkelfj** [comment]
I could add a parse_number function that branches out to parse_integer and parse_hex_integer etc., and returns the type in the status, but I don't see an immediate need, and it could easily be built on top of portable, if needed, while the opposite is not as easy.

**Comment by n3npq** [comment]
Yes, POSIX and portability and NUL termination and standards ... oh my!

I was surprised by treating hex (with or without 0x) and decimal integers with separate parsers.

The convincing reason for continuing with existing (to me) is the possibility of symbol collision
if pparseint.h were to use a POSIX API, say,
    static inline int64_t stroll(const char *nptr, char*endptr, int base)
(yes int64_t rather than long long).

At that level of (rather nitpick even if true) portability, even the "inline" (rather than a library routine) risks changed behavior through symbol collision or unexpected performance gain/loss.
