### ISSUE TITLE
enum's with negative values seem unusable

### ISSUE THREAD

**Issue by n3npq** [dvidelabs/flatcc#35]
Attempting an enum definition like this
    enum SUBTYPE:int {
       XREF          = -12,
      BIN_ARRAY     = -11,
      REGION        = -10,
    }
leads to  error messages like this

rpmtag_json_parser.h: In function ‘_RPM_SUBTYPE_parse_json_enum’:
rpmtag_json_parser.h:196:30: error: integer constant is so large that it is unsigned [-Werror]
                     *value = 18446744073709551605, *value_sign = 1;
                              ^~~~~~~~~~~~~~~~~~~~

**Comment by mikkelfj** [comment]
This is a large issue.

I will submit a quick fix that solves the above issue on the constants, but it also affects default value assignment in the reader and possible other places. Enum definitions in the reader are already handled, but I'm not sure it is done right since using UL, ULL suffixes are not fully portable.

Ideally `*value = 18446744073709551605, *value_sign = 1;` should be `*value = UINT64_C(18446744073709551605), *value_sign = 1;`

but then it must be ensured <inttypes.h> is handled correctly with and without fallback to "flatcc/portable/pstdint.h".

There are also issues with very large vectors in the builder with the size_t type for byte vectors longer than 2^31 bytes on 32-bit platforms, and 2^15 bytes on 16-bit platforms, but we also don't want to plaster every constant with a fat type qualifier.

Similar issues have been fixed earlier, I believe, but clearly not capturing all cases.

**Comment by mikkelfj** [comment]
Please let me know if this solves the immediate issue at hand.

I think the other cases are less likely to cause problems and it is better to spend some time thinking about how to best handle it.

In some cases it may be better to do nothing since bloating a lot of files with unlike needed type qualifiers doesn't help much (e.g. size_t size arguments in the builder interface). It can be fixed later if really needed.

However, I still believe default values such as 2^32-1 for ulong fields could cause problems in realistic cases.

**Comment by n3npq** [comment]
WORKSFORME. Thank you for the incredibly quick repair!

**Comment by mikkelfj** [comment]
The last commit wraps default values and enums in `UINT32_C(42)` type values. No reported issues, but there is a risk of compiler errors or warnings for large user supplied values.

There are no such wrappers for size_t types in the builder for string or vector lengths but it is unlikely to have a vector have the addressable memory range on any system.
