### ISSUE TITLE
Lazy offset redundancy removal in *_vec_create()

### ISSUE THREAD

**Issue by n3npq** [dvidelabs/flatcc#37]
While struggling mightily with creating arrays of unions of arrays of types top-down,
I found a simple hack to reuse the previous offset for identical values.

Here is the code snippet I eventually stumbled upon adding
`table STRING_ARRAY      { v:[string]    (required); }`
with some simple logic to reuse the previous offset if/when strings are identical
`    ....
    case RPM_STRING_ARRAY_TYPE:
        { nsc(string_ref_t) refs[he->c];
          for (size_t ix = 0; ix < he->c; ix++) {
              if (ix > 1 && !strcmp(he->p.argv[ix], he->p.argv[ix-1])) {
                  fb->saved += strlen(he->p.argv[ix]) + 1;
                  refs[ix] = refs[ix-1];
              } else
                  refs[ix] = nsc(string_create_str(B, he->p.argv[ix]));
          }
              ns(Tag_val_STRING_ARRAY_add(B,
                      ns(STRING_ARRAY_create(B,
                              nsc(string_vec_create(B, refs, he->c))
                      ))
              ));
        } break;
`

(aside)
RPM data contains many arrays of nearly identical items. The bytes fb->saved calculation
for my specific test case was modest but not trivial (the units below are in bytes):
`headerSizeof: 7564
  flatbuffer: 11730
       saved: 688
   json_nbuf: 25748
`
RPM has many sparse arrays of uint32_t that might benefit from a similar redundancy removal
(OTOH, KISS arrays of int* might preclude lazy redundancy removal, I'd have to measure)

Here's the code snippet creating uint32_t arrays (for reference), lazy redundancy removal for ints
would require changes to uint32_vec_create, and may not be feasible)
`    case RPM_UINT32_TYPE:
              ns(Tag_val_UI32_add(B,
                      ns(UI32_create(B,
                              nsc(uint32_vec_create(B, he->p.ui32p, he->c))
                      ))
              ));
          break;
`

The implementation is too obvious not to have been considered at some point in time ;-)

**Comment by n3npq** [comment]
Apologies for the misformatting: I will eventually figure out markdown browser entry \-(

**Comment by mikkelfj** [comment]
just highligt and clicke <>, or wrap in backticks.

**Comment by mikkelfj** [comment]
or you did that already? - then try 4 space indent.

**Comment by mikkelfj** [comment]
case RPM_STRING_ARRAY_TYPE:
        { nsc(string_ref_t) refs[he->c];
          for (size_t ix = 0; ix < he->c; ix++) {
              if (ix > 1 && !strcmp(he->p.argv[ix], he->p.argv[ix-1])) {
                  fb->saved += strlen(he->p.argv[ix]) + 1;
                  refs[ix] = refs[ix-1];
              } else
                  refs[ix] = nsc(string_create_str(B, he->p.argv[ix]));
          }
              ns(Tag_val_STRING_ARRAY_add(B,
                      ns(STRING_ARRAY_create(B,
                              nsc(string_vec_create(B, refs, he->c))
                      ))
              ));
        } break;

**Comment by mikkelfj** [comment]
Neat trick.

You should be able to do the same with uint32 vectors using memcmp because you are adding the complete array in one operation. Strings are really uint8 vectors under the hood with a guaranteed trailing 0 padding and some different user facing wrappers.

Depending on use case gzip may be better and simpler.

**Comment by mikkelfj** [comment]
btw: the ns wrappers are designed so it is possible to write `nsc(string_vec_create)(B, refs, he->c)` which depending on preference simplifies nesting.

**Comment by n3npq** [comment]
Is there a reason that the 2nd arg to string_vec_create isn't char *argv[count], forcing top-down builder code to generate a string_ref_t array of offsets before calling string_vec_create()?

string_vec_create() is an oddball, unlike other  *_vec_create() routines for arrays of primitive types.

**Comment by n3npq** [comment]
gzip and other compression is always possible.

Meanwhile the size of less plaintext compressed will almost always be smaller than more plaintext compressed.

**Comment by mikkelfj** [comment]
Yes, string_vec is special. It is the only vector type that can container other vectors. As I recall it follows the principle of table vectors which are also offsets, meaning ref types while building.

Supporting `char *argv[count]` could be possible using a new function like `string_str_vec_create` or similar - not sure about the exact naming scheme. The variant `string_strn_vec_create` which takes length arguments would then require two vectors as arguments, which would be stretching the idea a bit far perhaps.

The basic ref support should always be possible. How would otherwise add your custom compression scheme to string vectors?

**Comment by mikkelfj** [comment]
BTW: you are not forced to create an array, you should be able to use  string_vec_start, _push_create_str, ..., string_vec_end, or something close to that.

You can also use string_vec_extend to reserve the vector, but you need to call _edit to get a fresh pointer, or you get a crash like the low-count enum bug on a table vector, you reported recently. My first attempt at this failed (didn't read the doc, ...), so I used push instead.

**Comment by mikkelfj** [comment]
Anyway, as a feature enhancement, this won't fly. It it is too specific and affects performance and interface complexity.

There is a possibility to add a deduplicator by using an alternative emitter implementation and some negotiation between the builder and emitter. The emitter may roll back an added table, string, vector etc. if a dupe is found via a hash table. In this way deduplication will also works on on incrementally built strings and vectors using push.

Another option is to implement a compressor the traverses and deep copies a buffer without duplicates. I kind of like this approach the most. It could also interact with a dedupe attribute.

It is also possible to combine this with LZ4 compression because all the boundaries visited are ideal locations for LZ4 4-byte hashing. A reader could be able to access a compressed buffer directly using a hash table of decompressed regions.

Though I have thought of all of this before, it is not an immediate priority. But if you want to tackle some of it, there are vacancies.

**Comment by mikkelfj** [comment]
In fact, it would be possible to do in-place deduplication, shrinking the buffer, though likely not faster than copying.

**Comment by mikkelfj** [comment]
On dedupe, it could be done using blake2b hashing and merkle trees then it isn't necessary to compare content and then it can work even if the emitter streams the content over the network so the original copy is no longer available.

**Comment by mikkelfj** [comment]
such hashing must be done on the virtual address (i.e. ref_t values) because e.g. the offsets for two string vectors would differ even if their content is otherwise references to the same strings. This suggests the builder needs to cooperate with the hashing, or even that only the builder and not the emitter should be involved. The builder can only do it alone if it doesn't have to compare after a hash matches, i.e. when strong hash like blake2b or sha1.

**Comment by mikkelfj** [comment]
As this is a large issue, larger than this request, that is not likely to be addressed soon, I close this issue.
