### ISSUE TITLE
Achieving FLATCC_PORTABLE features in C++ application with non C11 gcc

### ISSUE THREAD

**Issue by rathdeep** [dvidelabs/flatcc#39]
I want to use flatcc project in C++ application (__cplusplus defined). But I am using gcc version < 4.6. So I use -D FLATCC_PORTABLE option (for e.g. because stdalign.h does not exist).
All portables files like "pstdalign.h" uses c++ macros for exclusion, hence not executing.
#ifndef __cplusplus
#endif /* __cplusplus */

I can manually remove __cplusplus from these ps header to work. But want to check if it will cause any issues.

Thanks.

**Comment by mikkelfj** [comment]
Hi rathdeep,

The portable library has not been carefully designed to handle C++ well and it may have inherited __cplusplus flags from various sources. Therefore I cannot give a single answer to you question as to whether it would be safe to remove. In some cases it may be fine, but most likely the answer is to use extern "C" as discussed below.

I would like flatcc to work with C++ compilers because Googles flatc does not support all C++ compilers, and you cannot reasonably require C linkage with all include flatbuffer source, so I think eventually the code should be improved to make this easier.

You can try to wrap all flatcc source included into C++ source using

```
extern "C" {
#include "monster_builder.h"
}
```

For specific portable files I'd be happy to make it useable directly in C++ when a good solution exists and has been tested. But it isn't trivial because some functions might exists in a std:: namespace in C++ and require other headers, e.g. <memory> for alignment which is similar to those in C, but different.

More generally, most of the portably files probably should have a extern "C" statement in the header:

```
#ifdef __cplusplus
extern "C" {
#endif
...
#ifdef __cplusplus
}
#endif
```

You could try the above in stdalign.h and see how that works, and also try the wrap around the monster_builder.h file, or whatever you are testing.

`include/flatcc/flatbuffers.h` might also be a place to add support for standard compliant C++ without requiring FLATCC_PORTABLE.

The diagnostic push/pop headers could also be modified with extern "C" because these are added at the start and end of each generated C header, although this is a bit of a hack:
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pdiagnostic_pop.h

Please let me know how this works out.

**Comment by rathdeep** [comment]
Sorry, did not get this solution correctly. Inside extern "C" block __cplusplus macro will still be defined. As a result, inside flatcc/portable/pstdalign.h,  alignas will not be defined. which in turn will result into including stdalign.h (inside generated reader.h) which is not available in older gcc. 

monster_reader.h:
#ifndef alignas
#include <stdalign.h>  --- i don't have stdalign.h, so want related macros to be defined.
#endif

**Comment by mikkelfj** [comment]
OK - I wasn't sure either.

From reading the following:
http://en.cppreference.com/w/cpp/language/alignas

alignas is a C++ keyword in C++11 and therefore pstdalign.h should not define alignas for C++11. Fortunately C++11 defines
`__alignas_is_defined`

So based on this information I would say the __cplusplus check can be removed as long as __alignas_is_defined is tested. I will update this file.

This only handles this specific file. There may be many other issues in portable, but I would happy to work with you to resolve any such issues if possible.

**Comment by mikkelfj** [comment]
I pushed a new experimental cpp branch with the above changes. Note that stdalign.h also implements aligned_alloc by including `paligned_alloc.h` which may also cause problems, but in you case you will likely be able to use of gcc posix_memalign.

**Comment by mikkelfj** [comment]
```
#ifndef alignas
#include <stdalign.h>
#endif
```

I think this test should have been

```
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
```
and possibly placed in `include/flatcc/flatcc_flatbuffers.h`.

**Comment by mikkelfj** [comment]
I also fixed the generated reader on master and cpp branch:
```
#ifndef alignas
#include <stdalign.h>
#endif
```

```
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
```

**Comment by rathdeep** [comment]
Thanks. Let me take this cpp branch.

**Comment by mikkelfj** [comment]
@rathdeep any news on this - should I just merge the cpp branch to main?

**Comment by rathdeep** [comment]
Sure. Till now i have not faced any issues. Thanks.

**Comment by mikkelfj** [comment]
I just committed this and removed cpp branch. I also added a similar fix top paligned_alloc.h which was just updated for another reason #40 .
