### ISSUE TITLE
Is it possible to supply an WinHex or Wireshark template for analysis binary data?

### ISSUE THREAD

**Issue by navigator117** [dvidelabs/flatcc#45]
Is it possible to supply an WinHex or Wireshark template for analysis binary data?

**Comment by mikkelfj** [comment]
I am not familar with these, but it it is not a trivial problem because the binary format cannot tell if a member of a table is primitive type, or an offset to some other type. So you essentially need to generate debug code for every table you need to inspect, and know in advance what type it is. There is an option to to use type hashes which could aid such as tool in deciding the root table type but would still need generated code.

It might be possible to use the JSON printer to dump buffers in various tools once you have decided the type. If you cannot decide the type, you need to incorparate the generated verifier as well in order to make safe guesses.
