### ISSUE TITLE
Is it possible to reduce copy overhead with flatcc_builder_finalize_buffer?

### ISSUE THREAD

**Issue by navigator117** [dvidelabs/flatcc#46]
For network buffer optimize:
I can get buffer directly by flatcc_builder_get_direct_buffer and send buffer data over socket API. But for large buffer,  how can I iterate emitter buffers  and send them one by one over socket, instead of call flatcc_builder_finalize_buffer to alloc and copy buffer data?

**Comment by mikkelfj** [comment]
First of all - copying a buffer is not very expensive. If you want to avoid allocation, you can write the final buffer to a buffer you supply.

For low latency transmission you can send part of the buffer before it has been written completely.

To do that you can create a custom emitter, it is not very difficult, but easy to make small mistakes in offsets. I suggest you modify the default emitter - it implements a direct buffer write interface and store data in pages.

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_emitter.h
https://github.com/dvidelabs/flatcc/blob/master/src/runtime/emitter.c

Also see a minimal example here, doing nothing useful: https://github.com/dvidelabs/flatcc/tree/master/test/emit_test

There are a few operations that are not valid on custom emitters, such as the direct buffer call you mention - these are documented in https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_builder.h

You can send these pages over the network. You just have to careful because of the back to front write, so pages must be combined in the reverse order they are created. The other concern is that by default virtual tables are written at the end, so you need to be prepared for pages growing in both directions. This can be disabled by `void flatcc_builder_set_vtable_clustering(flatcc_builder_t *B, int enable);`

You could also create another non-paged emitted that allocates a large buffer that is filled back to from. Then reallocated if needed.

To avoid recombining, a new StreamBuffer variant of flatbuffers is needed, but we don't have that for now: https://groups.google.com/forum/#!topic/flatbuffers/DncTqWTY7VU
