### ISSUE TITLE
fallthrough warnings

### ISSUE THREAD

**Issue by gambigo** [dvidelabs/flatcc#58]
It seems that with latest gcc 7.1.1 and clang 4.0.1  (C++17 updates) code can't be compiled:

src/flatcc/include/flatcc/portable/pprintint.h:100:58: error: this statement may fall through [-Werror=implicit-fallthrough=]
 #define __print_unaligned_copy_16(p, q) (*(uint16_t*)(p) = *(uint16_t*)(q))

adding "-Wimplicit-fallthrough=0" to CMakeLists.txt resolved problem for me.

**Comment by mikkelfj** [comment]
@gambigo 

I do not trivally have access to test this - can you help make a patch?

Is the issue limited to pprintint.h ?

Would you be able to make a patch for
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/pdiagnostic.h
(included via pdiagnostic_push.h)
?

Disabling the warning globally in the CMake configuration is not optimal because it may influence a parent project.
