### ISSUE TITLE
Compilation errors with gcc 4.7.2 and glib-2.0 (2.40.2).

### ISSUE THREAD

**Issue by macce** [dvidelabs/flatcc#6]
While compiling with gcc 4.7.2 together with glib-2.0 (2.40.2) I run into problems with the static assert feature.

In include/flatcc/portable/pstatic_assert.h:
```
...
#ifdef __has_feature

#if __has_feature(c_static_assert)
#define static_assert(pred, msg) _Static_assert(pred, msg)
#endif

#else
...
```

glib seems to define __has_feature but *not* _has_feature(c_static_assert) even though _Static_assert works for this particular version gcc. I don't know if this is as bug in glib or in flatcc, but just wanted to report it. My temporary workaround is just commenting out the #if __has_feature(c_static_assert) and corresponding #endif.

**Comment by mikkelfj** [comment]
I believe this is a known issue, but it shouldn't be problem to the end user, so I'd like to know more about why you need to address the issue. The special case is being deal with in:

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/portable/portable.h

and you may enter the "wrong" branch because you have not defined -std=c11 in which case pstdint is forced to rely on the flaky macro. If -std=c11 is defined, it will check for _Static_assert exactly because of the issue you mention.

It may be that portable.h isn't being included, but pstatic_assert.h is and perhaps some logic should be moved. It is hard to tell off-hand if there is an include somewhere else that needs to be changed.

In any case in think you should be able to deal with the situation by either defined -std=c11, or FLATCC_PORTABLE, or use as is and accept the macro fallback, which in most cases work quite well despite being a hack. You shouldn't have to resort to modifying pstatic_assert.h.

**Comment by macce** [comment]
Reading your comment I realize I failed to read all documentation where you mentioned the flags above. Anyway, I tried them but still with no success. Nevertheless this is probably still something I am doing wrong, so I guess the issue should just be closed unless other people also experience the same situation.

**Comment by mikkelfj** [comment]
I will leave it open for a while - you clearly do something different from the examples and test cases, but that does not necessarily make it wrong or unreasonable. If you find out what goes wrong or is able to provide a small example, please update. Likely you need to include portable.h somewhere directly, or indirectly by including generated headers.
