### ISSUE TITLE
 security considerations

### ISSUE THREAD

**Issue by navigator117** [dvidelabs/flatcc#63]
might be help if there were a section of security considerations in docs, like what kind of invalid protocol data may cause segment fault, buffer overflow, access violation.

**Comment by mikkelfj** [comment]
Yes that might be a good idea. I have chosen to leave many of the core principles of FlatBuffers being documented by referring to Googles FlatBuffers page but still a small section would be good.

Below I'll summarize the immediate concerns:

Essentially you cannot trust any buffer you have not created and not verified. And you can trust any buffer that you have verified, iff you use the interface correctly - it is C after all. Even if the buffer is created for a completely different schema, it should still be safe to access after being verfied, although it will likely not verify, and if it does, it will likely produce meaningless values.

In place modificiation is inherently unsafe, which is already mentioned in the documentation. The reason is that the verifier cannot detect maliciously crafted content where to seperate pieces of buffer content occupy some of the same space in the buffer. If this happens, in place modification can result in a corrupted buffer that is unsafe to access.

A buffer can also be constructed such that it takes infinitely long time to traveres recursively because the DAG allows extremely large graphs with moderate buffer sizes. The verifier is currently not fully protected against this. It only tests for a maximum recursion level, not a maximum of visited tables tables (Googles C++ verifier has such a limit). This means the verifier might never terminate.

Sending a HMAC signature with a buffer would allow the receiver to trust the buffer if the issuer of the signature is trusted, but that is beyond the scope of the flatcc library. In other cases the sender is known by other means and the buffer can also be trusted without verificiation.

**Comment by mikkelfj** [comment]
https://github.com/dvidelabs/flatcc/blob/master/doc/security.md
