### ISSUE TITLE
Publish builds of releases

### ISSUE THREAD

**Issue by andrewleech** [dvidelabs/flatcc#66]
Considering you already have CI builds running, would it be possible for you to keep the built applications as artifacts from travis/appveyor and publish them on the github releases?

This can be done automatically as part of the build:
https://victorhurdugaci.com/github-releases-travis
https://www.appveyor.com/docs/deployment/github/

**Comment by mikkelfj** [comment]
I'm not strictly opposed if you are willing to put in the work, but I am not entirely convinced either. 

The source is already trivially available via a github url I suppose. For binary builds the platform must make sense. For OS-X it doesn't because the binaries must be signed. For Linux the build is on some arbitrary Linux OS that happens to support gcc and clang in reasonably old and new versions and I'm not sure how portable the resulting binary is. I suspect a library would work on many Linux amd64 platforms. But then header files must be added - and it becomes a matter of building rpm and other package formats which I'd prefer separate package maintainers handle.

For Windows it might make a lot of sense, especially as a dll, but currently a dll is not being built, and it would some additional testing to ensure all necessary files are being generated.

So I would need to know more about the specific use case and if you, or someone else, is willing to support the work.

**Comment by andrewleech** [comment]
You make good points.  I see that flatcc is already available in homebrew for osx and yes, binary compatibility can certainly be a pain on linux, while building is usually relatively easy.

My use case is Windows in particular where I was evaluating flatcc for use in an embedded project. 
I wanted to be able to easily run the compiler to examine the generated code for suitability.
The need to install visual studio build tools as well as cmake is a really tedious overhead on windows, and my colleague (embedded designer who's never used visual studio) wrote it off instantly as too much effort.

I have since found the runtime source files and seen the use of dynamic memory allocation which rules this library out on our tiny platform anyway though. 

Thanks for the quick response!

**Comment by mikkelfj** [comment]
For Windows there would probably need to be declspec statements for public DLL functions making it possible, but non-trivial to support, but the runtime is small enough to be linked into any project as a few plain C files - which is documented, or you can just pick them here: https://github.com/dvidelabs/flatcc/tree/master/src/runtime

The flatcc schema compiler command line tool is a different issue, but you could probably also compile it with mingw or clang for Windows.

As to the dynamic allocation, the allocator is designed to be highly customizable especially for very constrained devices. You can get away with a static 4K buffer or possibly less depending on the data you carry and you do not have to depend on malloc at all. There are two ways to do this - either implement a custom allocator and give it to the builder as argument, or override the FLATCC_ALLOC methods which have been used fro FreeRTOS development.

https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_alloc.h
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_builder.h#L182-L203
https://github.com/dvidelabs/flatcc/blob/master/include/flatcc/flatcc_builder.h#L465-L476
https://github.com/dvidelabs/flatcc/blob/master/src/runtime/builder.c#L118-L173

**Comment by mikkelfj** [comment]
This might also help, but I have not tried. 
https://stackoverflow.com/questions/7081820/setting-default-compiler-in-cmake
Change CXX to  C

**Comment by mikkelfj** [comment]
The custom allocator works by providing a few different stacks and nothing else. You can experimentally figure out the size needed for each - some might only need a few bytes. Then you return a static buffer for each memory type and assert if there is unexpected additional memory requirements.

The emitter is a bit different - it fills data into buffers, but a single buffer is enough for small amounts of data, so it also doesn't need more than a static buffer. You can turn of clustered vtables, then it will always fill the buffer back to front instead of growing in two directions.

**Comment by andrewleech** [comment]
Thanks for all the suggestions, that helps a lot. I'll have a closer look again, currently for me it's between this and nanopb. 
Both of them meet my goal of stopping my colleague from "just cast a struct and send it down the serial port" and then me having to deal with it at the other end. 
It's a very small, very cheap 8 bit device it needs to fit in though so either solution may still be too big.
Cheers!

**Comment by mikkelfj** [comment]
8-bit could be a bit tight. But I'd like to hear about it if you go down that path and provide support and I'd like to document the use case with any details that you allow me to share. I could help with adding a more basic custom emitter to the library.

You can also use FlatCC with a schema to generate portable structs with a guaranteed layout and support for endian conversion and little to no resource consumption. You can use the structs directly or with a FlatBuffers header (MyStruct_create_as_root). Other languages do not support structs as root AFAIK, but the structs would be compatible with use in larger FB buffer you migth create at a gateway. Structs also support a generated JSON parser and printer on systems with enough resources. But structs do not support schema evolution.
