### ISSUE TITLE
Question on Binary format

### ISSUE THREAD

**Issue by zejal** [dvidelabs/flatcc#76]
In [https://github.com/dvidelabs/flatcc/blob/master/doc/binary-format.md#unions]( https://github.com/dvidelabs/flatcc/blob/master/doc/binary-format.md#unions) the doc states that: 

> If an element is of type NONE the value offset must be stored as 0 which is a circular reference. This is the only offset that can have the value 0.

From this statement and experimental test it seems that arrays cannot contain "null" tables. The following FBS file fails to parse correctly.
`
table foo
{
  x: int;
}

table bar
{
  foos : [foo];
}

root_type bar;

{
  foos : [ null ] // fails with error: expecting: { instead got: null
}
`

Is there any reason why null tables are not supported in arrays ?
Thanks

**Comment by mikkelfj** [comment]
It is a good question. I also have some concerns about the FlatBuffers null concept but the really short answer is that without null, it is safe to read from a vector if is present.

Before answering, it is important to understand that there is no direct relation between JSON null and FlatBuffers content. The current flatcc JSON parser rejects null in most cases exactly because there is no solid interpretation, but future versions of FlatCC will likely support null in more cases and normally encode it the same as if a value was not present at all - which does not make sense in a vector.

FlatBuffers does not have a strong concept of null, disregarding JSON syntax. A value can be present or absent in a tables vtable entry, and absence COULD be interpreted as null, but for scalars absence normally means default value. Some use cases where null is important, such as when converting to  and from database records, it is possible to force default values such that absence can be interpreted as null.

For vectors of strings and tables there is no well-defined concept of absence. For union vectors there is the NONE type which defines absence.

On a deeper technical level all references are stored as offsets, and a zero offset does not really make any sense. Using it to encode null in union vectors is a necessary hack.

That said, one could imagine supporting null vector elements in general, but then a reader must be prepared for them. Without null it is safe to read from a vector without special cases. For union vectors this is safe due to the NONE type. What does it mean for a vector field to be required if it can contain null values?

The current flatcc builder (disregarding JSON) also rejects null values when building vectors, at least in debug mode.

**Comment by mikkelfj** [comment]
Another thing:

I'm not sure if you are using flatcc or flatc to parse the schema. Unlike Googles flatc compiler, flatcc does NOT accept JSON after the schema, but if you separately tried to parse the last object, you would likely get an error like you describe.

**Comment by zejal** [comment]
Using flatc but I usually read the description of binary format from docs in flatcc project which gives precise details on the specification.

**Comment by zejal** [comment]
A related question is about unions. I see 3 essential valid situations if I read correct the specs:
Both union type and union value are absent (0 offset in v-table or NONE type). The semantics of this is union value being not set at all.
Both union type and union value are present (non 0 offset in v-table != NONE union type). The union value is set.
Union type is present and union value is absent (0 offset). What's the correct semantics for this please ? Is this union value not set at all or union value having default value of union type ? I tend to think it's the latter.

**Comment by mikkelfj** [comment]
If a union has a type other than NONE, its value must be present and valid. The following was written before union values other than tables were added, citation from verification section fo binary format doc. The same concept extends to structs and strings.

> verify that if the union type is NONE the value (offset) field is absent and if it is not NONE that the value field is present. If the union type is known, the table should be verified. If the type is not known the table field should be ignored. A reader using the same schema would see the union as NONE. An unknown union is not an error in order to support forward versioning.

(BTW: I edited your original post to fix the url)

**Comment by zejal** [comment]
OK thanks for having clarified. So there is only 2 valid situations (present/present or absent/absent) which makes sense to me. I think I could create invalid FB with union type != NONE and no value.

**Comment by mikkelfj** [comment]
You can have  present NONE value, although it doesn't make much sense. However, if you force defaults in order to handle null values, it does serve a purpose because a present NONE would not mean a null value. You can't really represent a typed NULL value in a union.

Also note that due to schema evolution a type might be present but unknown to the reader. In this case it does not matter what the value is because it will be ignored and treated as NONE.

A further complication that I am currently dealing with is in JSON parsing of union vectors: If you see a value of unknown type that is not NONE, it is difficult for the parser to treat it any different from a value of type NONE although this is a bit misleading.

**Comment by zejal** [comment]
What do you mean by present NONE value please ? AFAIK NONE only applies to union type.
Thanks

**Comment by mikkelfj** [comment]
It means that the vtable has non-zero vtable entry for the type field of a union, but the union type value in the table is 0.

**Comment by zejal** [comment]
I think this situation is not valid as you stated just earlier:
> If a union has a type other than NONE, its value must be present and valid.

**Comment by mikkelfj** [comment]
It is not a type other than NONE. It is the type NONE, because the type field with value 0 means NONE.

**Comment by zejal** [comment]
Isn't type field offset in vtable being 0 and type field value being NONE equivalent ?

**Comment by mikkelfj** [comment]
No, the vtable can be zero which means NONE, but it can also be non-empty and point to a value of 0.
This is like an integer with default value 0, you can omit the entry, or store 0 if you use force defaults. It only makes sense to force a default if you need to make default different from absent, such as representing NULL values.

**Comment by zejal** [comment]
Yes that's the general case for all fields in a table AFAIK. My question was for union fields as we have 2 fields so we (If not mistaken) potentially have 6 cases of which some are invalid, but it's not clear which ones are invalid.

Union type field offset in vtable     Type value               Union value field in vtable       Valid? (fail check if N)
0                                                      N/A                         0                                               Y
0                                                      N/A                         != 0                                          N
!= 0                                                  0 (NONE)                0                                               Y
!= 0                                                  0 (NONE)                != 0                                          N
!= 0                                                  != 0                         0                                               Y?
!= 0                                                  != 0                         != 0                                          Y

Sorry for being not clear.

**Comment by mikkelfj** [comment]
Yes that is roughly it. It is based on my best interpration of sensible values, and other implemetations might differ slightly.

I don't think the union value should be zero if the the type is not. I think flatcc verifier will reject it except when it does not know the type. It could (and might) also reject it there, but it is simpler to just ignore the field in that case and leave rejection to readers/verifiers that actually know the type since a null value cannot do any harm if you don't know the type.

**Comment by zejal** [comment]
I always wondered why unions were not implemented as a "special" struct with 2 fields, one being the type (uint8_t) and the other the value (uoffset_t). This would leave 1 field for unions in other containers (no _type field), and reduce the table cases above to 4 with 2 cases being non sensible.

**Comment by mikkelfj** [comment]
A different union design would have made many things easier, but it makes no sense to change it now.
