### ISSUE TITLE
Add support for kernel module 

### ISSUE THREAD

**Issue by LYZ1030** [dvidelabs/flatcc#89]
My goal is to support usage of flatcc in Linux kernel - mainly for the runtime. In order to do this, Abstracting away several libraries used by current flatcc such as assert.h, stdlib.h, stdio.h, string.h, memory.h is needed.

For now the plan is to add marocs such as passert and so on to replace old ones and then have a flag: #ifdef LINUX_KERNEL.

Any ideas? Here is the related link to the post in Google Group. https://groups.google.com/forum/#!topic/flatbuffers/_6LvkWeHPDQ

P.S. I'd quite like to use flatcc in my kernel module project, so I'm very willing to implement this in some parts :) and any help is appreciated.

**Comment by derosier** [comment]
This is a very odd choice, and one that goes against the fundamental design philosophy of the Kernel. flatcc is the type of thing that belongs in user-space, and attempting to do otherwise is a lot of work, of limited use to the general public, and has a large potential to open security holes.

I for one would not like to see the primary flatcc become a kernel module, nor do I want to see it accrete large amounts of abstractions and compatibility layers for such a questionable goal.

If you have a use-case that makes sense to you and want to proceed, well great and more power to you. That's the great thing about open-source: you can scratch your itch and you don't have to listen to a grumpy guy like me. So, go make a fork and do your thing. 

And on that note, I did go and look at your google-groups thread. Pretty much everything you're asking about has a kernel equivalent.

**Comment by mikkelfj** [comment]
I look forward to hear more about that module. FreeRTOS and newlib have been reported to work, so I don't think it will be too hard. The difficult part is in finding the proper abstractions.

I suggest you start stripping stdlib.h and memory.h and assert.h out of builder.c
move stdlib.h in flatcc alloc header inside the the first #ifndef. Then see where it takes you.

Use the ALLOC abstractions as an example.

Create a custom build with the essential runtime files first. No need to port everything in one go, or perhaps ever. Once you get a bit confident, you could create a PR so the builds on Travis / Appveyor can test more. They could run with a forced flag just for testing.

Perhaps not use passert after all (despite what I wrote) - FLATCC_BUILDER_ASSERT is probably sufficient, and some rtconfig flags. But I see you already did that. No worries, well see what works - just prefer FLATCC_ macros to passert() in the main parts of the source code. passert can be used low-level.

The flag for the kernel should probably be FLATCC_NO_STDLIB, FLATCC_NO_ASSERT or similar and then these flags  are detected somewhere suitable via an official L. kernel flag and used to redefine FLATCC_BUILDER_ASSERT etc. (probably one per runtime C file). Perhaps in flatcc_flatbuffers.h or at the top of the C file.

I think rtconfig is meant to be human friendly and is should not auto-detect - it can be replaced in users own build instead of flagging in build system. But you could perhaps have a default off flag there.

I'm sure I'm gonna change my mind a few times - but that is how it usually works until things settle.
I just don't have the setup to test all myself.

**Comment by mikkelfj** [comment]
I'd listen to @derosier, but from my perspective, the changes are just a cleanup for something that is mostly done anyway - i.e. malloc, and assert. Whether it is wise to place in the kernel is a different matter. mmap and context switch should give most benefits without running in kernel.

**Comment by LYZ1030** [comment]
Thanks for pointing out the disadvantages @derosier, though I believe these can then be used by kernel projects in some cases. 

Thanks for your detailed advice @mikkelfj. I'd agree that using FLATCC_BUILDER_ASSERT is sufficient,  passert is only of a few lines of code anyway. Also, FLATCC_NO_STDLIB, FLATCC_NO_ASSERT and etc flags are more consistent and clear. I'm working on it and will keep you updated.

**Comment by mikkelfj** [comment]
Maybe stdlib can just be removed witthout a flag if it is inluded in the default ALLOC. Only src/runtime, affected headers.

**Comment by mikkelfj** [comment]
Or maybe not - it could be some projects define a new alloc but still assume stdlib.h to be included, so a flag in builder with FLATCC_NO_STDLIB is perhaps better.

**Comment by mikkelfj** [comment]
@paulreimer It seems that you mostly work with C++ these days, but if you have an opinion on how to flag stdlib.h in builder.c and related runtime for embedded systems, your input would be welcome.

**Comment by LYZ1030** [comment]
I realize using Flatcc in kernel might be more complicated than I thought. Even though some kernel version libraries already implemented and can be used to replace user level libraries such as string.h, stdlib.h and etc, there're other challenging issues and I feel like it's bit more than what I can take right now.

One of the biggest question is that SSE is disabled in kernel while it seems to be required in 
flatcc_accessors.h : 
`flatcc/include/flatcc/flatcc_accessors.h:48:7: error: SSE register return with SSE disabled
 union __ ## N ## _cast { T v; uint ## W ## _t u; };    `

I've tried different methods and tried to understand what's going on behind the code but can't get anything to work. Any possible way to solve this?

**Comment by mikkelfj** [comment]
I completely understand this might be a bit much - I try do things outside the kernel when possible - things do not generally  run slower because of it.

As to your actual problem:

The only explicit use of SSE is in the JSON parser, and it is disabled by default and not really that useful as the parser is fast without it.

I suspect what you are seeing is a compiler optimisation. Perhaps you can compile the code with `-mno-sse` or something?

The union is a way to cast between two different types. When reading from raw memory with endian conversion it is for example necessary to convert a 64 bit integer to double value. The easy way is to use pointer to int64_t and cast it to a pointer to double, then read the value. But although almost always works, it is not portable or standard, and is undefined behavior. Writing the value to a union of both both types and then reading it as a different type is perhaps still a bit dubious but it is widely recognized as the safest way to do it, and any decent compiler should be able to deal with it.

I don't think the compiler has any trouble doing the cast since you are likely using a recent gcc version. It is more the way that it chooses to do it that causes problems. Hence helping it with some compiler flags might be useful.

Alternatively the kernel might have some macros for type casting. If so, flatcc_accessors.h file is probably in need for some modification.

But this is just guessing.

**Comment by mikkelfj** [comment]
Another issue is that I'm not sure that floating point is allowed in the kernel at all. Have you tried compiling with a schema that does not use floating point? There could be some parts in the builder that have to be removed, but it might also optimize out.

**Comment by mikkelfj** [comment]
The builder does not use floating point directly. It returns a void * to the location. The generated code use header only static inline functions to write to such a field. Hence the cast you mention. Therefore it might work to avoid having float or double in schema.
I haven't looked at the verifier though. I suggest you try to get working in stages - first with just reading, then only building, then verifying.

https://github.com/dvidelabs/flatcc/blob/ed32d6129fe1c6a00c7dec35f494aab5ac1f4c20/include/flatcc/flatcc_builder.h#L1345

**Comment by LYZ1030** [comment]
@mikkelfj Thanks for your detailed and quick response. Actually the schema that I'm trying right now doesn't involve floating point. I'm bit confused if there're chances that the C header files generated by Flatcc schema compiler requires some user-level libraries because formerly I was mainly modifying c files in src/runtime and header files in include/flatcc, which seems not connect to compiler part that generates the headers.

**Comment by mikkelfj** [comment]
What libraries are you concerned about?
The library dependencies are minimal, like stdint.h, and even that if you you use portable.

All headers include flatcc_flatbuffers.h and really only nothing else. Here alloc also goes through, but it isn't used by headers - it just keeps things in one place.

The reader is 100% headers and things like stdint.h or the portable alternative is needed, and on linux linux/endian.h is needed. But it is limited.

**Comment by mikkelfj** [comment]
If you mean that the generated builder depends on flatcc library - then yes - that is why there is a runtime builder.c file. You decide if it is a library, or you just compile with the c file directly. The reader is 100% headers (except limited C headers, hardly any runtime library, C or user).

**Comment by mikkelfj** [comment]
Using the generated reflection headers as an example, you can see the runtime library being called here to create a table.
https://github.com/dvidelabs/flatcc/blob/ed32d6129fe1c6a00c7dec35f494aab5ac1f4c20/include/flatcc/reflection/flatbuffers_common_builder.h#L382

**Comment by LYZ1030** [comment]
@mikkelfj Thanks for your explanation! I was worried about that generated headers themselves may requires some libraries stdlib.h and etc, which turns out not be the case. I'd take your advice to try to get working in stages and see how things go.

**Comment by mikkelfj** [comment]
Closing this, but feel free to reopen if the kernel project gains traction.
