### ISSUE TITLE
compile error (error: conflicting types)

### ISSUE THREAD

**Issue by dmitryme** [dvidelabs/flatcc#96]
Hello, I have a schema like this

namespace proto;

table Settings
{
   start: uint32 = 0;
   stop: uint32 = 0;
}

table Message1
{
   settings: Settings;
}

table Message2
{
   settings: Settings;
}

union Message
{
   Message1,
   Message2
}

table Transport
{
   message: Message;
}

root_type Transport;

C code is generated with flatcc (flatcc -a proto.fbs)

trying to compile with

#include "proto_builder.h"
#include <assert.h>
#include <stdio.h>

int32_t main()
{
   flatcc_builder_t b;
   flatcc_builder_init(&b);
   return 0;
}

and got an error

> In file included from proto_builder.h:10:0,
>                  from main1.c:1:
> proto_builder.h:27:41: error: conflicting types for ‘proto_Settings_start’
>  __flatbuffers_build_table(flatbuffers_, proto_Settings, 2)
>                                          ^
> flatbuffers_common_builder.h:381:19: note: in definition of macro ‘__flatbuffers_build_table’
>  static inline int N ## _start(NS ## builder_t *B)\
>                    ^
> In file included from proto_reader.h:7:0,
>                  from proto_builder.h:7,
>                  from main1.c:1:
> proto_reader.h:65:38: note: previous definition of ‘proto_Settings_start’ was here
>  __flatbuffers_define_scalar_field(0, proto_Settings, start, flatbuffers_uint32, uint32_t, UINT32_C(0))
>                                       ^
> flatbuffers_common_reader.h:39:17: note: in definition of macro ‘__flatbuffers_define_scalar_field’
>  static inline T N ## _ ## NK(N ## _table_t t__tmp)\

**Comment by mikkelfj** [comment]
Thanks, that doesn't look right. I'll have a look later today.

**Comment by mikkelfj** [comment]
The reason is because flatcc reserves a few names for its own operatoins, such as `_start` to start building a buffer. This can conflict with with accessor methods like `Settings_start()` to access a field name start.

A workaround is to rename start and stop to xstart and xstop in the schema, just for illustration.

A recent -g (for get) switch to flatbuffers resolves many of those conflicts but requires you to use `Settings_start_get()` etc. The _get method is always available, but -g removes the accessors witout _get to avoid potential conflicst.

Unfortunately this doesn't solve all problems because you use unions. I missed some places that should have used `_type_get()` instead of `_type()`. I will look into and get back to you.

But simply renaming the fields should get you started for now.

**Comment by dmitryme** [comment]
Thanks a lot,
renaming works!

**Comment by mikkelfj** [comment]
It should be fixed on master in  dd5f97d
So it is up to you whether you want to use non-conflicting field names, or use the flatcc -g option with _get suffix in accessor methods.

Please let me know if this works for you.

**Comment by mikkelfj** [comment]
See also documentation on topic: https://github.com/dvidelabs/flatcc#potential-name-conflicts
