### ISSUE TITLE
Oracle SunCC warns about an unreachable statement

### ISSUE THREAD

**Issue by vchrn** [dvidelabs/flatcc#97]
Good morning, [this break statement](https://github.com/dvidelabs/flatcc/blob/dd5f97d719fb27a0534fe839a5befdeb4f487880/src/compiler/codegen_c_reader.c#L1141) is in the middle of its `case` block and there are no comments around it. Is it intentional?

**Comment by mikkelfj** [comment]
Good day (as we have passed noon here). No this break statement is not intentional. It likely slipped in when adding support for linear scan of table fields with keys.

The effect if the break is that methods are not created for searching or scanning by key when there is a key attribute on a scalar field (from a brief look at the code). Since many users probably don't use key attributes it hasn't been reported as an issue.

It should be safe to remove, and I have done so in the latest commit.

Thanks for reporting.

**Comment by vchrn** [comment]
Perfect, thank you.
